### ISSUE TITLE
Binary releases

### ISSUE THREAD

**Issue by 0rzech** [AdaCore/ada_language_server#1000]
It would be great if ALS binaries were available to download from `releases` page, like [this one](https://github.com/AdaCore/ada_language_server/releases/tag/23.0.1) for macOS. It would save people using different IDEs and editors from manual compiling or extracting ALS from Theia/VS Code extensions.

_EDIT: Looks like this issue's number is 1000. Ha! 🎉 🙂_

**Comment by reznikmm** [comment]
@0rzech,
Is [this](https://github.com/AdaCore/ada_language_server/releases) works for you?

**Comment by 0rzech** [comment]
Thank you! It does. 🙂

**Comment by 0rzech** [comment]
Thank you, @reznikmm ! It does. 🙂
