### ISSUE TITLE
[Feature Request] Disabling pop-up "Some project source directories are not listed..."

### ISSUE THREAD

**Issue by PaulCayard** [AdaCore/ada_language_server#1006]
Every time I launch vscode with "Language Support for Ada" v23.0.8, the following pop-up appears:
"Some project source directories are not listed in your workspace: do you want to add them?"

Is it possible to disable it?

Thanks a lot!

**Comment by AnthonyLeonardoGracio** [comment]
Hello @PaulCayard,

This popup indicates that some source directories of your project hierarchy are not listed under the current VS Code workspace: our extension then proposes to add them. Have you tried to click on 'Yes'? Once these directories get added to the workspace, the popup won't be shown again.

Regards,

**Comment by PaulCayard** [comment]
Hi Anthony,
I don't want to add these directories to the workspace. If I click 'No', when I relaunch vscode pop-up is shown again.
Thanks anyway for the explanation!

**Comment by AnthonyLeonardoGracio** [comment]
Ok I see. Then we can probably add a 'Do not show this again' option in that case. We thought that usually people want to have access to all the sources from the project.

**Comment by reznikmm** [comment]
## An idea to discuss:

To propose adding directories only the user has an non-empty workspace.

## Reason: 

* If the user doesn't have a workspace then (1) he doesn't know about workspaces or (2) he does a quick "ad-hoc editing". In both cases he doesn't care about keeping workspace and the dialog is mostly useless to him.

* On the other hand, if the user has spent time to configure workspace then (1) he knows about workspaces and (2) he is going to do a "serious editing". In this case the popup should help him a lot to populate the workspace with folders.

**Comment by PaulCayard** [comment]
>

**Comment by PaulCayard** [comment]
> * In both cases he doesn't care about keeping workspace and the dialog is mostly useless to him.
This is my case. I use local git repositories as "vs project" and don't want to create a workspace.

(sorry for close and reopen the thread, it was a mistake)

**Comment by PaulCayard** [comment]
Yeah, I saw it in the edge branch. Thank you for the request implementation!

**Comment by reznikmm** [comment]
We have published `23.0.9` that includes these changes. It should be fixed.

**Comment by PaulCayard** [comment]
Thanks a lot! It works perfectly!
