### ISSUE TITLE
Format selection seems to be broken with "--source-line-breaks" option

### ISSUE THREAD

**Issue by JHag6694** [AdaCore/ada_language_server#1008]
Hello 

Testing release 23.0.8, it seems that in some cases, formatting using "Format selection" is broken when using "--source-line-breaks".
Additional information;
- No problem with 23.0.7
- No problem found with "--preserve-line-breaks"
- Once "Format selection" request failed, next "Format document" request will also failed

With 
- VSCode 1.69.2 (System setup) / Windows 10
- source code from https://github.com/JHag6694/AdaTest
- when formatting procedure You_Say_Hello, I get 
 ```
[Error - 12:35:38] Request textDocument/rangeFormatting failed.
  Message: 
  Code: -32603 
```
See : 
![FormatSelection](https://user-images.githubusercontent.com/26746642/180991297-0dc58c76-a133-4d26-88b9-7663976d65b8.gif)

**Comment by reznikmm** [comment]
Thank you, we will fix this.

**Comment by joaopsazevedo** [comment]
This issue is now fixed in the the edge branch.
Thank you for reporting and for the reproducer.
