### ISSUE TITLE
What LSP request implements "auto-add with-clauses"?

### ISSUE THREAD

**Issue by stephe-ada-guru** [AdaCore/ada_language_server#1039]
The main README.md  mentions "Code refactoring like insert named associations, auto-add with-clauses." However, https://github.com/AdaCore/ada_language_server/blob/master/doc/refactoring_tools.md does not mention this feature.

I'm working on adding support for ada_language_server to Emacs ada-mode, so I'd like to know how to do this.

**Comment by stephe-ada-guru** [comment]
Maybe it's als-refactor-imports?

**Comment by AnthonyLeonardoGracio** [comment]
Hello,

it's called `als-auto-import`. We'll update the doc to make the names more explicit.

Regards,
