### ISSUE TITLE
noob question: support for multiple .gpr?

### ISSUE THREAD

**Issue by gantsevdenis** [AdaCore/ada_language_server#1065]
Hi there,
I would like to know how I should organize my project to support multiple sub-project with each their own `.gpr` files.
Is this even possible? For example: [`https://github.com/flyx/OpenGLAda`](https://github.com/flyx/OpenGLAda) has 5 different child-projects, each depending on `opengl`.

This is just an example: if you tell me I should organize differently, no problem: I just would love to have auto-completion in my `tests`, when `with`-ing the parent project

**Comment by godunko** [comment]
Ada Language Server doesn't restrict use of project files to some patterns. Any hierarchy of the project files are supported.

However, Ada Language Server (as well as GNAT Studio) requires to have single top level project. Such root project can depends from any number of other projects.

OpenGLAda provides good example of quite complex use of features of project files, you can use it as an example.
