### ISSUE TITLE
Goto declaration or definition does not work together with Gnat extensions enabled

### ISSUE THREAD

**Issue by joakim-strandberg** [AdaCore/ada_language_server#1067]
When developing software with tagged types vscode has no problems with finding primitive subprograms of tagged types. But when using -gnatX to enable Gnat extensions to be able to untag record type definitions and still be able to use the object dot operation notation, vscode can no longer find the subprograms using "goto declaration or definition" and one gets instead the error message: No definition found for '...'

**Comment by joakim-strandberg** [comment]
Ok, thanks for the explanation. Not much to do at the moment then. I suggest closing this issue.

**Comment by AnthonyLeonardoGracio** [comment]
Thanks @joakim-strandberg, closing the issue for now then ;)
