### ISSUE TITLE
Where is python module e3?

### ISSUE THREAD

**Issue by stephe-ada-guru** [AdaCore/ada_language_server#1069]
I'm trying to run the ada_language_server tests, so I can duplicate a bug I'm getting with Emacs ada-mode and ada_language_server. it wants python module e3, but python pip says there's no such module. Where can I find it?

**Comment by stephe-ada-guru** [comment]
Found it: python modules e3-core and e3-testsuite

**Comment by reznikmm** [comment]
yes, GitHub CI does `pip install --user e3-testsuite`
