### ISSUE TITLE
allow specifying gpr file in initializationOptions 

### ISSUE THREAD

**Issue by stephe-ada-guru** [AdaCore/ada_language_server#1079]
In Emacs, it would be convenient if als allowed specifying  the gpr file in the initializationOptions parameter of the initialize request; other language servers allow similar settings by that method. Right now, I have to write custom code to send a workspace/didChangeConfiguration message to set the gpr file.

**Comment by AnthonyLeonardoGracio** [comment]
Hello @stephe-ada-guru,

Indeed, that looks like a reasonable enhancement. We'll have a look!
