### ISSUE TITLE
Range formatting request raises assertion_error in Extract_Original_Selection_From_Output

### ISSUE THREAD

**Issue by stephe-ada-guru** [AdaCore/ada_language_server#1086]
[range_formatting_02.tgz.txt](https://github.com/AdaCore/ada_language_server/files/10174877/range_formatting_02.tgz.txt)

The range formatting request fails with:

[ALS.MAIN] Range_Formatting_Response: Response  4  Error
[ALS.OUT] {"jsonrpc":"2.0","id":4,"error":{"code":-32603,"message":""}}

The problem is the assert in laltools-partial_gnatpp.adb Extract_Original_Selection_From_Output. The code does not require the restriction that the assert tries to impose (it should use 'length, not 'size). Deleting the assert allows the test to succeed.

**Comment by joaopsazevedo** [comment]
This issue is now fixed in the the edge branch.
Thank you for reporting and for the reproducer.
