### ISSUE TITLE
Range formatting request drops last line

### ISSUE THREAD

**Issue by stephe-ada-guru** [AdaCore/ada_language_server#1087]
[range_formatting_03.tgz.txt](https://github.com/AdaCore/ada_language_server/files/10187387/range_formatting_03.tgz.txt)

The result edit list deletes the last comment line; it should not.

**Comment by AnthonyLeonardoGracio** [comment]
Hello, 

The file seems corrupted, could you resend it?

**Comment by AnthonyLeonardoGracio** [comment]
Oops sorry, renaming it makes things work. We'll have a look!

**Comment by AnthonyLeonardoGracio** [comment]
We can reproduce, thanks for the reproducer!

**Comment by stephe-ada-guru** [comment]
The attached patch (renamed to .txt for github file filter) fixes the problem.

[range_formatting_03.diff.txt](https://github.com/AdaCore/ada_language_server/files/10226796/range_formatting_03.diff.txt)

**Comment by joaopsazevedo** [comment]
@stephe-ada-guru Thanks for reporting all the partial formatting issues and for the reproducers. We've been actively working on the partial formatting logic and that is why we haven't addressed the issues you've reported. Now that we've finished the last batch of improvements, we will start going through your issues. We will reply to each one soon.

**Comment by ogorodnik** [comment]
> 

Hello. This issue has been already fixed in the development version. The fix will be accessible with the next release. Thank you for the report especially for reproducer.
