### ISSUE TITLE
No project found in root directory.

### ISSUE THREAD

**Issue by NicoPy** [AdaCore/ada_language_server#1096]
I'm trying to make ALS fully work with Eclipse.
When opening an Ada file (.adb, .ads), everything seems to work correctly except I get the following error message : 
`No project found in root directory. Please create a project file and add it to the configuration.`
The ALS executable is run from the project root directory, where the `.gpr` project file is located.
Doesn't the ALS search for _any_ `.gpr`file and use it ?

Note : My PC is running Windows 10.

**Comment by reznikmm** [comment]
Currently ALS expects project file to be sent in `didChangeConfiguration` notification as explained [here](https://github.com/AdaCore/ada_language_server/blob/master/doc/settings.md). If no `projectFile` sent and there is a single project file in the root folder, then ALS will use it. ALS doesn't search `gpr` files in folders other then root.

We have an enhancement request to specify project file in `initializationOptions` during initialization #1079, but this isn't implemented yet.

BTW Could you share details about ALS Eclipse integration? PR with README.md update would be great :wink:

**Comment by NicoPy** [comment]
> Currently ALS expects project file to be sent in didChangeConfiguration notification as explained [here](https://github.com/AdaCore/ada_language_server/blob/master/doc/settings.md). If no projectFile sent and there is a single project file in the root folder, then ALS will use it. ALS doesn't search gpr files in folders other then root.

Just to be sure, the root folder is the current working directory . Right ?

> We have an enhancement request to specify project file in initializationOptions during initialization https://github.com/AdaCore/ada_language_server/issues/1079, but this isn't implemented yet.

Yes, I noticed it. In my use case, the ideal would be to pass a configuration file in the ALS parameters. Maybe I can inject a file content in stdin at ALS startup (not tried yet) ?

> BTW Could you share details about ALS Eclipse integration? PR with README.md update would be great 😉

I'm in the process of writing a blog post about it. As I do not want to write a dedicated extension, this is a quite long and complex setup. It almost fully works ☺️

**Comment by furioncycle** [comment]
Hi is this being worked on? 

I ran into this when trying to use Helix with the goal of adding Ada as a supported language.

**Comment by AnthonyLeonardoGracio** [comment]
> Hi is this being worked on?
> 
> I ran into this when trying to use Helix with the goal of adding Ada as a supported language.

Hello!

We have properly implemented the `initialize` request, allowing users to specify the project's path via the `initializationOptions`: this should be included in the current extension's version. We have also just added a new `--config` option, allowing to set the server's configuration directly in a JSON file at startup (not released yet).

**Comment by NicoPy** [comment]
That's good news. I'll try the `--config` option with the next release.
