### ISSUE TITLE
Building Ada Language Server

### ISSUE THREAD

**Issue by jarmilaticha** [AdaCore/ada_language_server#1134]
Hello. I'm trying to build an ada language server on my computer. Would it be possible to advise what I am doing wrong? or what exact structure do I need?
It is currently throwing me this error.
![ada_error](https://user-images.githubusercontent.com/126875327/224958428-fe63a1ec-1a27-4ac6-9d6a-cfb3ecaafdfb.PNG)

 Thank you

**Comment by reznikmm** [comment]
ALS has a lot of dependencies. I would suggest you to use Alire to fetch and build them. The community index has a [crate for ALS](https://alire.ada.dev/crates/ada_language_server.html). If you need more recent ALS version then you can try my dedicated ALS Alire index.

https://github.com/reznikmm/als-alire-index/

**Comment by jarmilaticha** [comment]
I use your alire. I started alr build, see picture. but still nothing happened, should I put it somewhere else?
![alr_build](https://user-images.githubusercontent.com/126875327/224962207-ff3ca557-1bdf-462e-9695-697f342d9f41.PNG)
 now build in linux. then I would like to build it on Windows

**Comment by jarmilaticha** [comment]
![image](https://user-images.githubusercontent.com/126875327/224965076-460b0375-e859-4782-a9da-942169e7042b.png)
I found the log here. can you give me a description so I should proceed? Thank you

**Comment by jarmilaticha** [comment]
I found the log here. can you give me a description so I should proceed? Thank you
![image](https://user-images.githubusercontent.com/126875327/224965592-8d58b02f-0fb5-449f-85a3-a087137cacf3.png)

**Comment by reznikmm** [comment]
On Linux:
* make sure you have `alr` and `git make curl libgmp-dev unzip libc6-dev python3` packages installed.
* run `alr toolchain --select` and select `gnat_native=12.2.1` and `gprbuild=22.0.1`
* run `alr get --build ada_language_server`

**Comment by jarmilaticha** [comment]
Thank you. build he asked. is there any other way to transform the build into *.exe format?

**Comment by jarmilaticha** [comment]
Thank you. FIle *.exe format I found. in the Make file it says to appear on this path cp -f $(ALS)$(EXE) integration/vscode/ada/$(PLATFORM). why doesn't it appear there?

**Comment by jarmilaticha** [comment]
Thank you. it is ok. pleas close ticket @reznikmm

**Comment by reznikmm** [comment]
Alire builds project by calling `gprbuild <PROJECT_FILE>` and doesn't use `make` and `Makefile`. You can try to run `alr exec bash` and run `make` under that shell.
