### ISSUE TITLE
Latest version of ALS VSCode 

### ISSUE THREAD

**Issue by Joebeazelman** [AdaCore/ada_language_server#1135]
Just downloaded the latest version of ALS 23.0.15. It complains about the following errors:

Error: there is no registered task type 'gnatprove'. Did you miss installing an extension that provides a corresponding task provider?
Error: there is no registered task type 'gprbuild'. Did you miss installing an extension that provides a corresponding task provider?
Error: there is no registered task type 'gprbuild'. Did you miss installing an extension that provides a corresponding task provider?
Error: there is no registered task type 'gnatprove'. Did you miss installing an extension that provides a corresponding task provider?
Error: there is no registered task type 'gprbuild'. Did you miss installing an extension that provides a corresponding task provider?
Error: there is no registered task type 'gprbuild'. Did you miss installing an extension that provides a corresponding task provider?

**Comment by Joebeazelman** [comment]
Error: there is no registered task type 'gnatprove'. Did you miss installing an extension that provides a corresponding task provider?
Error: there is no registered task type 'gprbuild'. Did you miss installing an extension that provides a corresponding task provider?
Error: there is no registered task type 'gprbuild'. Did you miss installing an extension that provides a corresponding task provider?
Error: there is no registered task type 'gnatprove'. Did you miss installing an extension that provides a corresponding task provider?
Error: there is no registered task type 'gprbuild'. Did you miss installing an extension that provides a corresponding task provider?
Error: there is no registered task type 'gprbuild'. Did you miss installing an extension that provides a corresponding task provider?

**Comment by reznikmm** [comment]
Please recreate your `tasks,json` file. We have optimized auto detected tasks implementation and changed task types to `gnat`, so it broke backward compatibility.
