### ISSUE TITLE
Alire "edit" command no longer launches VSCode with Project

### ISSUE THREAD

**Issue by Joebeazelman** [AdaCore/ada_language_server#1136]
Alire no longer launches VSCode with the project file.  After launching, you must open the project file manually.

**Comment by AnthonyLeonardoGracio** [comment]
Hello @Joebeazelman,

You don't need to use `alr edit` now, just opening VS Code in a workspace that has an Alire `.toml` file should do the trick with the latest version of the extension.

Regards,
