### ISSUE TITLE
vscode integration: `executable` property is used instead of `mainFile` 

### ISSUE THREAD

**Issue by Fratee** [AdaCore/ada_language_server#1154]
in `tasks.json` the required property name is `mainFile` is not consistent with the existing property `executable`.

see:
https://github.com/AdaCore/ada_language_server/blob/54e453b633f5f1e149813bff8b35300731cb6b9f/integration/vscode/ada/package.json#L446:L461

**Comment by AnthonyLeonardoGracio** [comment]
Hello!

We have now fixed this. The fix will be included in the next version of the extension.

Thanks for reporting this!
