### ISSUE TITLE
Add Subprogram Box command only applies to package body

### ISSUE THREAD

**Issue by rocher** [AdaCore/ada_language_server#1156]
There are two cases:
  1. When editing any subprogram of a package body, the `add subprogram box` command is applied only to the package, not to the subprogram.
  2. When editing a single procedure in a *.adb file, the `add subprogram box` command does nothing, possibly because no package is found (?).

I checked if a setup parameter could change this behavior, but none found.
Is there a new key-combination to apply this command to subprograms instead of packages? Is this a bug?

In my opinion, it should apply to subprograms (even inside a another subprogram) or task bodies first, then to package when cursor is outside subprogram/task but inside a package.

**Comment by AnthonyLeonardoGracio** [comment]
Hello @rocher,

Indeed, we have a fix for that. We introduced a very pernicious bug due to a refactoring. The command will work again in the next extension release.

Sorry for the inconvenience.

Regards,

**Comment by reznikmm** [comment]
:wrench: Should work again in 23.0.21!

**Comment by rocher** [comment]
Now it works great!!  Thanks!!
