### ISSUE TITLE
Renaming rarely works 

### ISSUE THREAD

**Issue by Joebeazelman** [AdaCore/ada_language_server#1159]
When I try to rename an identifier (the name of a function, procedure, variable, or type) using VS Code's *Rename Symbol* menu option, it complains that it can't rename it without providing a reason. On other occasions, it lets me go through the process of renaming it but nothing happens. There has only been a few times when it successfully renamed an identifier.

**Comment by reznikmm** [comment]
We have an improvement that shows more information of failed refactoring in the problem windows. This will be in the next release. We are interested in fixing renaming issue. Please send us any reproducer for this issue.

**Comment by Joebeazelman** [comment]
I would have to send you my project which is confidential.

**Comment by johnperry-math** [comment]
> Please send us any reproducer for this issue.

In my experience, just about any Ada code at all will reproduce it. I used VS Code extensively during the 2023 Advent of Code, and the Rename feature didn't rename anything except the text I had clicked on. It wasn't able even to rename the label after an `end` keyword.

For example, the following steps reproduce the issue for me:
1. `alr init --bin test_rename`
2. `cd test_rename`
3. `codium .`
4. open src/test_rename.adb
5. click on `Test_Rename` in line 1
6. press `f2`
7. rename `Test_Rename` to anything at all
8. observe that line 4 still has `end Test_Rename`

**Comment by johnperry-math** [comment]
Wow, I forgot I had commented on this. Renaming seems much more robust in recent editions of the server & extension. It's not quite perfect, so if I come across a MWE I'll mention it.

**Comment by Joebeazelman** [comment]
Awesome! Haven't tried it recently. I usually use change all or find in replace which doesn't rename it at the symbolic level.

**Comment by AnthonyLeonardoGracio** [comment]
Thanks for the feedback @johnperry-math ! I suggest we close this issue then and let's re-open one if you have a specific bug. Renaming can fail sometimes on some very complex Ada or project structures, but it generally works and if there is an error it should be quite visible from the VS Code interface.

Regards,
