### ISSUE TITLE
Constantly crashing on save

### ISSUE THREAD

**Issue by hw762** [AdaCore/ada_language_server#1187]
Hello, I am trying to learn Ada with some simple projects and tried the plugin. Every time I change anything in project settings, try to reformat, or save a file, I am  constantly getting errors like these:

    Log directory is 
    [Error - 10:29:20 PM] Request textDocument/formatting failed.
      Message: raylib.adb:1:1: Error formatting node (CompilationUnit). Keeping the initial input selection unchanged
    pp-formatting.adb:1247
      Code: -32603 
    [Error - 10:29:20 PM] Request textDocument/formatting failed.
      Message: raylib.adb:1:1: Error formatting node (CompilationUnit). Keeping the initial input selection unchanged
    pp-formatting.adb:1247
      Code: -32603 

No error squiggles anywhere. I have to do `alr build` to find any errors, fix them, reload the editor, and only then will the errors go away.

**Comment by hw762** [comment]
Basically, one error window pops up for every character I type into the editor window.

**Comment by AnthonyLeonardoGracio** [comment]
Hello! 

We have released a new version of the extension, with a new formatting engine based on `GNATformat` (see https://github.com/AdaCore/ada_language_server/issues/1216 for more details on this).

Closing this, assuming that it's fixed now. Do not hesitate to re-open with a basic reproducer (e.g: simple project) if not.

Regards,
