### ISSUE TITLE
[Bug]: Noticeable input-delay when entering whitespace

### ISSUE THREAD

**Issue by 0xfadead** [AdaCore/ada_language_server#1200]
### Environment

- OS and Version: Arch Linux 6.9.10-arch1-1 and ada-language-server 24.0.6
- IDE Version: Neovim v0.10.0 with LuaJIT 2.1.1720049189 with mason (commit: 0950b15) and mason-lspconfig (commit: 8db1261)
- Ada & SPARK Extension Version: f2018

### Bug Summary and Reproducer

Bug Summary:
When entering a whitespace before other tokens the immediate next one disappears for a split second before the next tokens move.
Even when having no next tokens it still lags.
I recorded a video of this: https://asciinema.org/a/BJOVnrs5bNBjiR7TR8lgRXak5

Steps to reproduce:
1. Install the `ada-language-server` extension from mason
2. Open an Ada Project
3. Enter a space before any other token(s)

Expected behavior:
Slightly _less_ noticeable lag when entering whitespace.

### Configuration and Logs

```shell
[Even with `ALS.IN=yes` and `ALS.OUT=yes` there is no output -- there's only a logfile with no content]
```

### Other VS Code Extensions

- Default treesitter-grammar

### Additional context

- I looked at the Mason "install-script" and from what I gathered it doesn't alter ada-language-server
- I disabled any keybinds starting with the space key in the linked video at 00:29 and the issue still persists

**Comment by AnthonyLeonardoGracio** [comment]
Hello @0xfadead,

Really strange, I can't reproduce from VS Code, using the exact same version of the Ada Language Server. So I suspect a bad interacting between the Neovim client and the server.

The first step in order to debug this would be to have proper logs: I suggest you to create the traces config fiels as described [here](https://github.com/AdaCore/ada_language_server/blob/master/doc/traces.md).

Once we have proper logs it would be easier to debug this, so let's first solve this issue.

Regards,

**Comment by 0xfadead** [comment]
Hi @AnthonyLeonardoGracio

> The first step in order to debug this would be to have proper logs: I suggest you to create the traces config fiels as described [here](https://github.com/AdaCore/ada_language_server/blob/master/doc/traces.md).

I have this in my `~/.als/ada_ls_traces.cfg`:
```
ALS.IN=yes
ALS.OUT=yes
ALS.MAIN=yes
ALS.LAL_PP_ON_FORMATTING=yes
```

But I get no output even though a file called `als.2024-07-22<timestamp>.log` is created.

Are there any extra configuration options I need to enable to get any sort of output?

Thanks in advance

**Comment by AnthonyLeonardoGracio** [comment]
> Hi @AnthonyLeonardoGracio
> 
> > The first step in order to debug this would be to have proper logs: I suggest you to create the traces config fiels as described [here](https://github.com/AdaCore/ada_language_server/blob/master/doc/traces.md).
> 
> I have this in my `~/.als/ada_ls_traces.cfg`:
> 
> ```
> ALS.IN=yes
> ALS.OUT=yes
> ALS.MAIN=yes
> ALS.LAL_PP_ON_FORMATTING=yes
> ```
> 
> But I get no output even though a file called `als.2024-07-22<timestamp>.log` is created.
> 
> Are there any extra configuration options I need to enable to get any sort of output?
> 
> Thanks in advance

Hello @0xfadead,

Indeed, my bad, we have revamped the way traces files work in the development version but it has not been released in the Marketplace yet. With your version you just need to rename `~/.als/ada_ls_traces.cfg` into `~/.als/traces.cfg`, then you will have non-empty log files.

I'll adjust the documentation about traces files to make it version specific. Sorry again.

Regards,

**Comment by AnthonyLeonardoGracio** [comment]
> Hi @AnthonyLeonardoGracio,
> 
> I renamed the file and here's the log: [als.2024-07-23T165948.12540.log](https://github.com/user-attachments/files/16350845/als.2024-07-23T165948.12540.log)

Thanks for the log. Nothing suspect unfortunately. I am wondering if the small delay can come from the `textDocument/signatureHelp` request: could you try to disable this feature from the Neovim client, to see if it gets better?

Regards,

**Comment by 0xfadead** [comment]
I have disabled `textDocument/signatureHelp` with `vim.lsp.handlers['textDocument/signatureHelp'] = nil`

Here's the log with only `ALS.MAIN`:
[als_main.log](https://github.com/user-attachments/files/16351077/als.2024-07-23T172422.15123.log)

Here's the log with `ALS.MAIN`, `ALS.IN` and `ALS.OUT`:
[als_all.log](https://github.com/user-attachments/files/16351099/als.2024-07-23T172849.15411.log)

**Comment by 0xfadead** [comment]
Sorry for the ping @AnthonyLeonardoGracio.
I think the first message didn't ping you because I included it in an edit.

**Comment by AnthonyLeonardoGracio** [comment]
> Hi @AnthonyLeonardoGracio,
> 
> I have disabled `textDocument/signatureHelp` with `vim.lsp.handlers['textDocument/signatureHelp'] = nil` The problem still persists though.
> 
> Here's the log with only `ALS.MAIN`: [als_main.log](https://github.com/user-attachments/files/16351077/als.2024-07-23T172422.15123.log)
> 
> Here's the log with `ALS.MAIN`, `ALS.IN` and `ALS.OUT`: [als_all.log](https://github.com/user-attachments/files/16351099/als.2024-07-23T172849.15411.log)

I don't see anything strange unfortunately. I just see that the `textDocument/semanticTokens` request is sent right after by the Neovim client: try to disable it to see if things improve. But at this stage I would say it's a client bug, not a problem coming from the server. The behavior does not exist in VS Code for instance.

**Comment by 0xfadead** [comment]
Okay, thanks.
I'll close the issue since, as you said, it's probably a bug in something else.

Have a great rest of your days,
Cheers

**Comment by 0xfadead** [comment]
The issue was fixed by someone on reddit: https://www.reddit.com/r/ada/comments/1e3cthr/comment/lgio025/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
