### ISSUE TITLE
gnat tasks obsolete but mentioned in the documentation?

### ISSUE THREAD

**Issue by mgrojo** [AdaCore/ada_language_server#1202]
My first time trying VSCode and maybe I'm misinterpreting something, but here we have a reference in the documentation about gnat tasks.

https://github.com/AdaCore/ada_language_server/blob/5100ea1e890a8a19da3a5f952dc3ad10f583839d/integration/vscode/ada/media/launch-debug.md?plain=1#L3

In another place, which I cannot reproduced now, I got a message saying something like "gnat tasks are obsolete, use ada or spark instead".

So I guess the documentation could be obsolete on that point.

**Comment by eliericha** [comment]
Hello,

It seems that this piece of documentation is unfortunately outdated. `gnat:` and `gpr:` tasks are indeed obsolete and the tasks that should be used are `ada:` and `spark:`.

I will update the documentation shortly and the update will appear in the next release of the VS Code extension.

**Comment by eliericha** [comment]
Hello @mgrojo ,

I reworked the walkthrough of the Ada & SPARK extension and it now includes a hello world project to help get familiar with the main concepts. You can access it in VS Code with the `Welcome: Open Walkthrough` command and then search for Ada.

The new walkthrough is available in the latest release on the VS Code marketplace, however note that we also have known issues in that release unfortunately. In some situations you may see errors about project loading. You may be able to dismiss the errors using the `Developer: Reload Window` command in VS Code.

I also updated the tutorial [on the wiki](https://github.com/AdaCore/ada_language_server/wiki/Getting-Started) to remove mentions of obsolete tasks.

I hope this helps.
