### ISSUE TITLE
[Bug]: "Ada" automatic debug configuration in VSCode doesn't work

### ISSUE THREAD

**Issue by Joebeazelman** [AdaCore/ada_language_server#1203]
### Environment

- Mac OS  14.6.1
- VS Code Version: 1.92.2
- Ada & SPARK Extension Version: 14? (latest)

### Bug Summary and Reproducer

Bug Summary:

VSCode's automatic debug configurator for Ada doesn't work. It reports: 

> "The project **default.gpr** does not have a Main attribute..."

My project file is not named `default.gpr` and it **does** contain a `Main` attribute. I suspect it got the default name from ALS'  default configuration settings in VSCode. Regardless, it couldn't possibly have detected  a missing `Main` attribute because the` default.gpr` doesn't exist in my folder.
 
Steps to reproduce:

Expected behavior:

### Configuration and Logs

```shell
NA
```

### Other VS Code Extensions

NA

**Comment by eliericha** [comment]
Hello @Joebeazelman ,

First could you clarify the version of the extension? The latest one published is `24.0.6`.

Then onto your actual problem, the fact that the extension reports `default.gpr` as the loaded project means that it was unable to load your project successfully. `default.gpr` is a fallback that allows some features to work, but not other (e.g. the debug configurations).

When you open an Ada source file, does the Problems show any messages indicating a failure of loading your project?

Could you also provide the [ALS trace file](https://github.com/AdaCore/ada_language_server/blob/master/doc/traces.md) ? That would help us determine why your project failed to load.

And finally I'd like to mention that we are improving the robustness and diagnostics of the project loading logic, as we realize that currently the failure to load a project is not visible enough in some cases and you may be misled into believing that you have a working setup when it is in fact the fallback `default.gpr`. This situation will improve over the next releases.

**Comment by eliericha** [comment]
Hello,

We just released a new version of the Ada & SPARK extension on the VS Code marketplace. The problem reported here should be fixed. So I will close the issue, feel free to reopen it if you're still experiencing the problem.
