### ISSUE TITLE
[Bug]: Problems when project file specified in initializationOptions

### ISSUE THREAD

**Issue by brownts** [AdaCore/ada_language_server#1209]
### Environment

- OS and Version: Windows 10, Ubuntu 22.04
- IDE Version: Emacs 30
- Ada & SPARK Extension Version: 24.0.6, 25.0.20240915, maybe more

### Bug Summary and Reproducer

**Bug Summary:**

When specifying configuration in `initializationOptions` instead of `workspace/didChangeConfiguration`, I'm expecting the project file to be used.  However, it appears its may be partially used.  I still see indexing in the log and there is no diagnostic about not finding the project file.  However, the `textDocument/definition` to other files all seem to fail. 

I've included an example project and logs.  Starting with the test.adb source file, the ALS is started up.  I wait for the `$/progress` to indicate completion and then I try to jump to definitions.  First, I try it on the call to "Do_Something" and next I try it on the "My_Lib" with clause.  Both fail with empty results being returned from the server.  Finally, I issue an "als-project-file" command and the ALS returns the path to a "default.gpr" file in the root directory (see the Ada trace file) instead of the project file identified in the `initializationOptions`.

**Steps to reproduce:**

I've included an example application.  Assuming the configuration is all sent in `initializationOptions` without any further `workspace/didChangeConfiguration`.

**Expected behavior:**

I expect the Ada Language Server `textDocument/definition` to successfully locate the references to the "with'd" package.  Furthermore, I expect the "als-project-file" to report back the project file specified in the `initializationOptions`.  Additionally, if it's using the "default.gpr" for some reason, I expect to see a diagnostic indicating it couldn't find the project file.

### Configuration and Logs

[als.2024-09-30T173123.1029207.log](https://github.com/user-attachments/files/17197100/als.2024-09-30T173123.1029207.log)

### Additional context

[initializationOptions.zip](https://github.com/user-attachments/files/17197097/initializationOptions.zip)

**Comment by setton** [comment]
Hello @brownts - thank you for sending this through. We're working on this and will make sure this is solved in the next iteration.

**Comment by brownts** [comment]
> In particular, ALS settings must be wrapped into `"initializationOptions": {"ada": { ... }}`.

Just to clarify, it now requires an "ada" prefix in "initializationOptions", where before it did not, correct?

**Comment by eliericha** [comment]
Yes. We decided to change this for consistency with the way settings are expected in the `workspace/didChangeConfiguration` notification. Now both have the "ada" prefix.

**Comment by brownts** [comment]
Great, thanks for the confirmation.
