### ISSUE TITLE
Title of releases

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/ada_language_server#1212]
Previously, releases were titled e.g. `als-24.0.6-macOS_aarch64.zip`, but in [25.0.20240915](https://github.com/AdaCore/ada_language_server/releases/tag/25.0.20240915) they’re quite anonymous, making it easy to lose them in a packed downloads folder.

Please return to the older style of naming.

**Comment by reznikmm** [comment]
indeed :disappointed:

**Comment by eliericha** [comment]
Hello @simonjwright ,

Thank you for your feedback. Indeed it would be better to include the version in the package names. We'll make that change.

**Comment by mgrojo** [comment]
Not only the version, but the product name itself :smile:

**Comment by eliericha** [comment]
Indeed :)

Just note that the next release will not have this fix because it is based on a branch that has already been frozen. We will make the fix for the next one.

**Comment by eliericha** [comment]
As indicated by the commits above, the issue has been fixed and should be reflected in the next release.
