### ISSUE TITLE
Failure of Shared Libraries?

### ISSUE THREAD

**Issue by SolarAquarion** [AdaCore/ada_language_server#217]
libadalang.gpr:14:17: shared library project "libadalang" cannot import static library project "gnatcoll_gmp"
libadalang.gpr:14:17: shared library project "libadalang" cannot import static library project "gnatcoll"
libadalang.gpr:14:17: shared library project "libadalang" cannot import static library project "xmlada_dom"
libadalang.gpr:14:17: shared library project "libadalang" cannot import static library project "xmlada_input"
libadalang.gpr:14:17: shared library project "libadalang" cannot import static library project "xmlada_unicode"
libadalang.gpr:14:17: shared library project "libadalang" cannot import static library project "xmlada_sax"
libadalang.gpr:14:17: shared library project "libadalang" cannot import static library project "xmlada_schema"
libadalang.gpr:14:17: shared library project "libadalang" cannot import static library project "gpr"
libadalang.gpr:14:17: shared library project "libadalang" cannot import static library project "gnatcoll_iconv"
langkit_support.gpr:12:17: shared library project "langkit_support" cannot import static library project "gnatcoll"
langkit_support.gpr:12:17: shared library project "langkit_support" cannot import static library project "xmlada_dom"
langkit_support.gpr:12:17: shared library project "langkit_support" cannot import static library project "xmlada_input"
langkit_support.gpr:12:17: shared library project "langkit_support" cannot import static library project "xmlada_unicode"
langkit_support.gpr:12:17: shared library project "langkit_support" cannot import static library project "xmlada_sax"
langkit_support.gpr:12:17: shared library project "langkit_support" cannot import static library project "xmlada_schema"
langkit_support.gpr:12:17: shared library project "langkit_support" cannot import static library project "gpr"
langkit_support.gpr:12:17: shared library project "langkit_support" cannot import static library project "gnatcoll_iconv"

**Comment by pmderodat** [comment]
Hello,

I assume you get these error messages while trying to compile ALS. It’s helpful in such reports to describe what you have tried, on which platform, and how you installed dependencies (in particular the versions).

My guess here is that you only built/installed the relocatable (shared) library for Libadalang while by default, all dependencies (gnatcoll_gmp, xmlada_dom, …) appear as static libraries. GPRbuild does not allow to mix library types, hence the error messages. In this case you have several options:

* Build/install Libadalang as a static library. To do this, just pass `--library-types=static,relocatable` to the `manage.py` script.
* run `make LIBRARY_TYPE=relocatable`. This is the Makefile’s default though, so it’s not clear if you tried something different.

I hope this helps,
