### ISSUE TITLE
procedure declaration snippet outputs invalid Ada

### ISSUE THREAD

**Issue by Entomy** [AdaCore/ada_language_server#227]
When tab completing the "Procedure Declaration" snippet, it generates `{7: is abstract}`, which I assume is meant to be an option when completing the snippet, but instead is literally written.

**Comment by setton** [comment]
Hi @Entomy - thank you for the heads-up! For info, at the moment we haven't spent a lot of time on completion features; we're going to focus on it in the coming year.

**Comment by Entomy** [comment]
Man I envy you. If I sent food out and the customer said there was something wrong with it, and I told them I'd fix it within the year, I'd loose my job.

**Comment by Entomy** [comment]
I looked for a snippets file and I'm not seeing it. I'm not sure how you implemented the feature, but based on the incorrect syntax that was written, whatever you are doing seems to work the same way. You're going to want something like this:

~~~~
"Procedure Spec": {
		"prefix": "procedure-spec",
		"scope": "ada",
		"body": [
			"procedure ${1:Name}(${2:Param} : ${3:Type})${4| is abstract;,;}"
		],
		"description": "Procedure declaration"
	},
~~~~

I don't have access to anything to test this at the moment, but the `${x|_,_,_|} pattern is what you'd be interested in. It seems like the entry was using the field replacement syntax, not the choice selection syntax.

**Comment by setton** [comment]
> Man I envy you. If I sent food out and the customer said there was something wrong with it, and I told them I'd fix it within the year, I'd loose my job.

Sir, this is not a Wendy's :-)

**Comment by setton** [comment]
> I looked for a snippets file and I'm not seeing it. I'm not sure how you implemented the feature, but based on the incorrect syntax that was written, whatever you are doing seems to work the same way. You're going to want something like this:
> 
> ```
> "Procedure Spec": {
> 		"prefix": "procedure-spec",
> 		"scope": "ada",
> 		"body": [
> 			"procedure ${1:Name}(${2:Param} : ${3:Type})${4| is abstract;,;|}"
> 		],
> 		"description": "Procedure declaration"
> 	},
> ```
> 
> I don't have access to anything to test this at the moment, but the `${x|_,_,_|}` pattern is what you'd be interested in. It seems like the entry was using the field replacement syntax, not the choice selection syntax.

Thank you for this! I don't have knowledge of the syntax that's needed here, I think you're more of an expert than anyone working on this part of the code at the moment... if you would like to join forces and contribute, that would be great!

**Comment by Entomy** [comment]
> Sir, this is not a Wendy's :-)

I do fine dining :-)

**Comment by Entomy** [comment]
> Thank you for this! I don't have knowledge of the syntax that's needed here, I think you're more of an expert than anyone working on this part of the code at the moment... if you would like to join forces and contribute, that would be great!

With the way your company has repeatedly treated me in the past, that will never happen.

I do this only because I know there are some who prefer your extension over my own because despite mine offering far better syntax highlighting, yours does have at least some level of functional LSP. At the end of the day, it's my desire to provide the best tooling for people as I can muster, even if that means it's a "competitors". I understand why they make the decision they make, and it's not something I can immediately counter-offer. They still deserve good tooling.

**Comment by reznikmm** [comment]
@Entomy thank you for the efforts! I've never seen `${x|_,_,_|}` pattern before.

If you have any other idea how to improve the extension, don't hesitate.

**Comment by Entomy** [comment]
https://code.visualstudio.com/docs/editor/userdefinedsnippets#_choice
