### ISSUE TITLE
Incorrect/incomplete highlighting of package names

### ISSUE THREAD

**Issue by Entomy** [AdaCore/ada_language_server#228]
![image](https://user-images.githubusercontent.com/25399505/68974810-9a792500-07bf-11ea-8950-b3d08f44ff22.png)

I'm not sure what the intent was here. If the intent was to provide highlighting to all package names, then it doesn't work for the list-like include statements. Furthermore it seems to think the package name is actually a function, which makes me think the intent might not have been to highlight package names at all.

**Comment by Entomy** [comment]
![image](https://user-images.githubusercontent.com/25399505/68974948-f348bd80-07bf-11ea-89f7-4c2b8d575d34.png)

I thought it might be only highlighting the first entry but it seems it's not, that it's only highlighting very specific package names.

**Comment by reznikmm** [comment]
This regexp left in the configuration file when I played with highlighting to see how it works. I should replace it with something more useful.
```
    }, {
        "name": "support.function.ada",
        "match": "\\b(?i:(Ada|Text_IO|Strings))\\b"
    }],
```
