### ISSUE TITLE
Missing classification of elseif as keyword

### ISSUE THREAD

**Issue by Entomy** [AdaCore/ada_language_server#230]
![image](https://user-images.githubusercontent.com/25399505/68975218-ac0efc80-07c0-11ea-9492-eb6d3656d668.png)

`elseif` seems to have been forgotten about when defining keywords

**Comment by setton** [comment]
`elseif` is not an Ada keyword -`elsif` is :-)

**Comment by Entomy** [comment]
You are correct! I mistyped. And it seems `elsif` is correctly recognized so this isn't an issue.
