### ISSUE TITLE
Possible misclassification of certain keywords?

### ISSUE THREAD

**Issue by Entomy** [AdaCore/ada_language_server#231]
![image](https://user-images.githubusercontent.com/25399505/68975278-d496f680-07c0-11ea-8f75-0e0db238aba0.png)

It seems like you've gone for a split classification approach of keywords, so that certain keywords are classified and highlighted as operators, some as regular keywords, and some as control keywords. I appreciate this because it allows certain themes to specifically highlight certain classifications.

However I am confused as to why what I would think are obvious controls, such as `if` and `loop`, are not classified as control keywords.

**Comment by setton** [comment]
Right, perhaps `return` should be a `keyword.control.ada` - `if`, `then`, `else`, `loop`, `for`, etc as well. @reznikmm do you have input for this?
