### ISSUE TITLE
No classification of operators or assignment

### ISSUE THREAD

**Issue by Entomy** [AdaCore/ada_language_server#232]
![image](https://user-images.githubusercontent.com/25399505/68975489-63a40e80-07c1-11ea-9db2-254dad353610.png)

Operators and the assignment symbol seem to be lacking classification as operators

**Comment by setton** [comment]
Indeed!

(Should the assignment symbol be highlighted as an operator? What do other languages do?)

**Comment by Entomy** [comment]
Seems like the majority of languages (at least major ones I looked at) do `keyword.operator.assignment`. I suspect so that themes which discriminate assignments theming can do so.
