### ISSUE TITLE
No support for numerical bases, supradecimal notation, nor e-notation

### ISSUE THREAD

**Issue by Entomy** [AdaCore/ada_language_server#236]
![image](https://user-images.githubusercontent.com/25399505/68979895-d8c91100-07cc-11ea-88c5-20fc239fbbe6.png)

As you can see, the base specifiers aren't being highlighted, and I suspect the only reason why the base is highlighted at all is it's recognized as a discrete and unique number.

For what it recognizes of one of the parts of a number, `52_` it's not marking this as invalid, despite it being invalid according to the ARM

![image](https://user-images.githubusercontent.com/25399505/68980446-812ba500-07ce-11ea-9bdb-75b3ba491ac9.png)

The `A` isn't being recognized despite being part of a hexadecimal literal, which causes me to think that any supradecimal notation isn't recognized.

And lastly `e-` isn't recognized as part of e-notation (I'm not sure if this should be recognized as an operator {which conceptually it is} or as part of the numeral {which the ARM defines it as}). And yes e-notation is allowed for based numeric literals.

![image](https://user-images.githubusercontent.com/25399505/68980580-d7004d00-07ce-11ea-957f-1b8a349866b3.png)

**Comment by reznikmm** [comment]
You are right, for now regexp is too simple: `([0-9][0-9_]*(\.[0-9][0-9_]*)?)`.
Feel free to contribute :wink:

**Comment by Entomy** [comment]
This are real quick and might have some minor issues.

Decimal Literal
~~~~
\d(_?\d)*(\.\d(_?\d)*)?([eE](\+|\-)?\d(_?\d)*)?
~~~~

Based Literal
~~~~
(?i)(\d(_?\d)*#)[0-9a-f](_?[0-9a-f])*(\.[0-9a-f](_?[0-9a-f])*)?(#)([eE](\+|\-)?\d(_?\d)*)?
~~~~

**Comment by Entomy** [comment]
This does assume `[eE](\+|\-)?` is part of the number, and isn't classified as an operator instead. If operator classification is desired instead, the easiest way to do this through the tmLanguage engine is to capture both of the numeric sections and classify those individually. As I can't find any tmLanguage files (maybe I'm missing them but this is thrice now I've looked) I'm not sure how you're actually classifying lexemes.
