### ISSUE TITLE
VSCode extension error: couldn't start client Ada Language Server

### ISSUE THREAD

**Issue by Naasha** [AdaCore/ada_language_server#239]
Hello, i'm trying to use the Visual Studio Code extension (installed using the provided .vsix file) but when i start VSCode i always get the following error "couldn't start client Ada Language Server" with the following output console:
`[Error - 10:11:08] Starting client failed
Error: spawn UNKNOWN
	at ChildProcess.spawn (internal/child_process.js:394:11)
	at Object.spawn (child_process.js:548:9)
	at d:\Users\T0123624\.vscode\extensions\maximreznik.ada-21.0.2\node_modules\vscode-languageclient\lib\main.js:354:40
`
I have GNATPRO 19.2 set in my path.
What am I missing ?

Thx for the help

**Comment by reznikmm** [comment]
Hello!
Can you run the server from Windows CMD console like this:
```
d:\Users\T0123624\.vscode\extensions\maximreznik.ada-21.0.2\win32\ada_language_server.exe
```

**Comment by Naasha** [comment]
Thanks for the fast reply !
Indeed i can't run it because of the system admin restriction on my computer.
Now that i understand the problem i'll search a way to move my vscode extension to a folder that i can execute ^^

Sorry for the inconvenience.
