### ISSUE TITLE
Visual Studio 2017 - Integration

### ISSUE THREAD

**Issue by Alex-Gamper** [AdaCore/ada_language_server#30]
Hi AdaCore

I've done a quick mock-up of a language server in Visual studio 2017 (NOT to be confused with Visual Studio Code) using the sample / instructions given at https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-an-lsp-extension?view=vs-2017
After some minor tweaks, to-do with project references, and not the actual code itself) this seem to work!

However I've noticed that this GitHub version does not seem to implement a response to the "initialize" json request, and hence VS2017 (as apposed to VSCode) aborts/fails loading the addin/extension.

Not sure what's going on here, and maybe I've misread the Ada code

Please advise

Thanks Alex

**Comment by raja-s** [comment]
@Alex-Gamper for reference here's the `initialize` request handler implementation:
https://github.com/AdaCore/ada_language_server/blob/84b6bc3499c9a1e6340a7a96eba5e5239723ce47/source/ada/lsp-ada_handlers.adb#L48-L85

**Comment by reznikmm** [comment]
The provided instructions contain a setting to enable traces (see "Enabling diagnostics tracing" section).

@Alex-Gamper, could you enable traces and look what's going wrong?

**Comment by Alex-Gamper** [comment]
I did enable traces, however the only entry I saw was the Initialize_request coming from Visual Studio 2017
and no return response ! I suspect their may be something different between VSCode and VS2017 wrt
the client IDE implementation of the LSP, rather than anything that the Ada_language_server is doing?

Alex

**Comment by reznikmm** [comment]
Please make sure that all .DLL needed for Ada LSP server are in the PATH.

Another suggestion is to get requests from VS2017 as text file and try to run Ada LSP server from command line with redirected stdin from that file.

On my side I've installed VS2017, but I'm haven't done any LSP integration stuff yet. If you share your code somewhere I can try to compile and reproduce.

**Comment by Alex-Gamper** [comment]
Hi reznikmm

Apologies for the late reply, time Zones sometimes makes it difficult to respond quickly, Anyway, please note the following

1) Yes all dll's are in my path and I can see the lsp-Ada_driver.exe running while I edit ada documents

2) I'll try this approach when I get a bit more time, I assume you meant doing this under a msys2 bash
shell, as apposed to a windows cmd shell ?

3) I've created a new git repo https://github.com/Alex-Gamper/Ada-LanguageServer.git which you can
use to test the VS2017 integration. Note this VS2017 solution/project creates a VSIX in the output dir
which you can then install. OR you can simply F5 (ie  run) the project and VS2017, which will start a new 
instance of VS (running under a test/experimental/test instance of VS2017 and doesn't interfere with
your normal VS2017 install ! But be patient using approach, as it may take some time to load ?

Thank

Alex

**Comment by reznikmm** [comment]
With a little hack in Ada Language Server I've got a trace of VS2017 requests. It seems it doesn't send any notification about file opening. That's why it doesn't work, I guess.

```json
Content-Length: 2540

{
  "jsonrpc": "2.0",
  "method": "initialize",
  "id": 2,
  "params": {
    "processId": 6804,
    "rootPath": "C:\\Projects\\libadalang\\ada_language_server",
    "rootUri": "file:///C:/Projects/libadalang/ada_language_server",
    "capabilities": {
      "workspace": {
        "applyEdit": true,
        "workspaceEdit": {
          "documentChanges": true
        },
        "didChangeConfiguration": {
          "dynamicRegistration": false
        },
        "didChangeWatchedFiles": {
          "dynamicRegistration": false
        },
        "symbol": {
          "symbolKind": null,
          "dynamicRegistration": false
        },
        "executeCommand": {
          "dynamicRegistration": false
        }
      },
      "textDocument": {
        "synchronization": {
          "willSave": false,
          "willSaveWaitUntil": false,
          "didSave": true,
          "dynamicRegistration": false
        },
        "completion": {
          "completionItem": {
            "snippetSupport": false,
            "commitCharactersSupport": false,
            "documentationFormat": null
          },
          "completionItemKind": null,
          "contextSupport": false,
          "dynamicRegistration": false
        },
        "hover": {
          "contentFormat": [
            "plaintext"
          ],
          "dynamicRegistration": false
        },
        "signatureHelp": {
          "signatureInformation": {
            "documentationFormat": [
              "plaintext"
            ]
          },
          "dynamicRegistration": false
        },
        "references": {
          "dynamicRegistration": false
        },
        "documentHighlight": {
          "dynamicRegistration": false
        },
        "documentSymbol": {
          "symbolKind": null,
          "dynamicRegistration": false
        },
        "formatting": {
          "dynamicRegistration": false
        },
        "rangeFormatting": {
          "dynamicRegistration": false
        },
        "onTypeFormatting": {
          "dynamicRegistration": false
        },
        "definition": {
          "dynamicRegistration": false
        },
        "codeAction": {
          "dynamicRegistration": false
        },
        "codeLens": {
          "dynamicRegistration": false
        },
        "documentLink": {
          "dynamicRegistration": false
        },
        "rename": {
          "dynamicRegistration": false
        }
      },
      "experimental": null
    },
    "initializationOptions": null,
    "trace": "off"
  }
}Content-Length: 195

{
  "jsonrpc": "2.0",
  "method": "workspace/didChangeConfiguration",
  "params": {
    "settings": {
      "ada": {
        "trace": {
          "server": "Verbose"
        }
      }
    }
  }
}Content-Length: 280

{
  "jsonrpc": "2.0",
  "method": "textDocument/definition",
  "id": 3,
  "params": {
    "textDocument": {
      "uri": "file:///C:/Projects/libadalang/ada_language_server/source/protocol/lsp-types.ads"
    },
    "position": {
      "line": 37,
      "character": 13
    }
  }
}Content-Length: 219

{
  "jsonrpc": "2.0",
  "method": "textDocument/documentSymbol",
  "id": 4,
  "params": {
    "textDocument": {
      "uri": "file:///C:/Projects/libadalang/ada_language_server/source/protocol/lsp-types.ads"
    }
  }
}Content-Length: 202

{
  "jsonrpc": "2.0",
  "method": "textDocument/didClose",
  "params": {
    "textDocument": {
      "uri": "file:///C:/Projects/libadalang/ada_language_server/source/protocol/lsp-types.ads"
    }
  }
}Content-Length: 57

{
  "jsonrpc": "2.0",
  "method": "shutdown",
  "id": 5
}Content-Length: 57

{
  "jsonrpc": "2.0",
  "method": "shutdown",
  "id": 5
}```

**Comment by reznikmm** [comment]
@Alex-Gamper I've found a bug related to URI on Windows. With this fix it works well on just opened files.

You can specify project file in settings like this:
```
{
   "ada.trace.server": "Verbose",
   "ada.projectFile": "gnat\\spawn.gpr"
}
```
You can use file name, or file name relative to working directory. It can have URI schema (`file:gnat\\spawn.gpr` or `file:///C:\Path\\gnat\\spawn.gpr`).

Thank you for the integration code!
