### ISSUE TITLE
Add .editorconfig

### ISSUE THREAD

**Issue by Entomy** [AdaCore/ada_language_server#334]
You guys use unique styling conventions. By adding an [`.editorconfig`](https://editorconfig.org/) file all supporting editors will automatically use the appropriate project style conventions, which reduces contributor and reviewer friction. Supporting editors include [VS Code](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig), [Emacs](https://melpa.org/#/editorconfig), [Vim](https://www.vim.org/scripts/script.php?script_id=3934), and more. There's no negative impact to this. Non supporting editors will adhere to their user preferences, and supporting editors only use the `.editorconfig` preferences in that workspace, preserving user settings otherwise.

**Comment by setton** [comment]
I'm in favour.
