### ISSUE TITLE
Go To Definition/Declaration/Type Definition not usable for .a files

### ISSUE THREAD

**Issue by Flurb** [AdaCore/ada_language_server#339]
It seems only .ads/.adb files are supported for the Go To Definition functionality.
.a files are not supported, but could be interpreted the same.

**Comment by Entomy** [comment]
The only other use of `.a` as an extension I'm aware of, involves binary compiler output. It should be possible to add this extension without conflict with others.

**Comment by reznikmm** [comment]
Ada Language Server supports custom file extensions for Ada sources only if they are defined in the project file. See [Naming Schemes](https://docs.adacore.com/gprbuild-docs/html/gprbuild_ug/gnat_project_manager.html#naming-schemes) in the documentation.

My advice:

1. Create a project file and define desired naming scheme in the Naming package of your project file.
2. Provide the project file to Ada Language Server by placing it in the working directory or point configuration to it. (See README.md about this).
3. Enable log files and check if Ada Language Server loads the project file.
