### ISSUE TITLE
Implement problem matcher

### ISSUE THREAD

**Issue by Entomy** [AdaCore/ada_language_server#354]
VS Code has a method for integrating analyzer output with the text editors gutter, through the [problem matcher](https://code.visualstudio.com/Docs/editor/tasks#_defining-a-problem-matcher) API. This would allow the errors and warnings that `gnatmake` produces to be put directly into the editor in the files and on the lines that is being reported.

It seems like, despite the official docs only mentioning doing this in the `tasks.json` file, per project, it can actually be provided via the extension inside of the `package.json`'s `contributes`, as a `problemMatchers` array.

**Comment by setton** [comment]
The regexp that we use in GNAT Studio for GNAT messages is:
`^([^:]:?[^:]*):(\d+):((\d+):)? (((medium )?warning|medium:)?(info|Note|check)?(\(style|low:|low warning:)?.*)`
I guess this should give a good first approximation. Not sure whether we can use the VScode API to do exactly what we would want, which is to mark "warnings" with the medium severity, "info", "style", with the low severity, and anything else with a high severity...

**Comment by reznikmm** [comment]
we already has this in `package.json`:

```
        "problemMatchers": [
            {
                "name": "ada",
                "label": "Gnat Ada Problem Matcher",
                "fileLocation": [
                    "relative",
                    "${workspaceRoot}"
                ],
                "pattern": [
                    {
                        "regexp": "^([^:]:?[^:]*):(\\d+):(\\d+):\\s+(warning|)(?:[:]\\s+)?(.*)$",
                        "file": 1,
                        "line": 2,
                        "column": 3,
                        "severity": 4,
                        "message": 5
                    }
                ]
            }
        ]
    },
```

We added this in #224. I supposed it works.

**Comment by Entomy** [comment]
Oh jeez. I never noticed. Oops! Alright I'll close this.
