### ISSUE TITLE
Set up VS Code automated testing

### ISSUE THREAD

**Issue by Entomy** [AdaCore/ada_language_server#386]
Perhaps it's time for us to look into setting up VS Code automated testing - the code is becoming too important to be tested manually. Don't hesitate to send pointers if you happen to have experience with this.

_Originally posted by @setton in https://github.com/AdaCore/ada_language_server/pull/377#issuecomment-606966176_

**Comment by Entomy** [comment]
Can someone add `help wanted` to this? There's resources people use to search for that specific label.

**Comment by setton** [comment]
> Can someone add `help wanted` to this? There's resources people use to search for that specific label.

Done.

For the record, https://github.com/redhat-developer/vscode-extension-tester this looks promising.
