### ISSUE TITLE
Procedure separates usage not found by reference search

### ISSUE THREAD

**Issue by abdurham2** [AdaCore/ada_language_server#431]
Procedure reference searches, when the procedure is declared as a separate, are only returning the .adb and .ads file where the procedure is declared.  Implementation searches, in this same case, only return the .adb file where the procedure is declared, and the .adb file where the procedure is implemented.  Neither reference search returns uses of the procedure in other files.  Function separates behave the same as procedures.

**Comment by reznikmm** [comment]
@abdurham2 Thank you for the issue. Could you provide some example?

**Comment by abdurham2** [comment]
I have a very complex workspace with linked projects, and through some trial and error, I thought that this was the reason behind not finding the procedure usage.  After trying to create a sample project that I could share, I was unable to recreate the issue with a simple project structure.  I think I will need to take some time to experiment and create a sample project that can demonstrate the issue.  I will close this issue and create a new one if I can find a way to recreate it.

**Comment by Entomy** [comment]
I wonder if its occuring at the linked project boundary then.
