### ISSUE TITLE
Constraint error

### ISSUE THREAD

**Issue by alincolesa** [AdaCore/ada_language_server#453]
Hello,
The error I'm facing when I'm trying to edit some large files:
> [Error - 4:29:39 PM] Request textDocument/documentSymbol failed.
>   Message: CONSTRAINT_ERROR
> [/net/sdp/homes/icolesa/.vscode-server/extensions/adacore.ada-21.0.12/linux/libgnatcoll.so.0]
> 0x7fa8188df77f gnatcoll__projects__is_aggregate_project at ???
> 0x7fa818940cbc gnatcoll__projects__aggregated_projects.localalias.1086 at ???
> [/net/homes/icolesa/.vscode-server/extensions/adacore.ada-21.0.12/linux/ada_language_server]
> Lsp.Ada_Handlers.Load_Project at lsp-ada_handlers.adb:2579
> Lsp.Ada_Handlers.Ensure_Project_Loaded at lsp-ada_handlers.adb:489
> Lsp.Ada_Handlers.Get_Open_Document at lsp-ada_handlers.adb:230
> Lsp.Ada_Handlers.On_Document_Symbols_Request at lsp-ada_handlers.adb:2110
> Lsp.Error_Decorators.Document_Symbols_Request at lsp-error_decorators.adb:45
> Lsp.Error_Decorators.On_Document_Symbols_Request at lsp-error_decorators.adb:341
> Lsp.Servers.Handle_Request at lsp-servers-handle_request.adb:175
> Lsp.Servers.Processing_Task_Type.Process_Message at lsp-servers.adb:1072
> Lsp.Servers.Processing_Task_TypeT at lsp-servers.adb:1148
> [/net/sdp/homes/icolesa/.vscode-server/extensions/adacore.ada-21.0.12/linux/libgnarl-2019.so]
> 0x7fa816a413f4 system__tasking__stages__task_wrapper at ???
> [/lib/x86_64-linux-gnu/libpthread.so.0]
> 0x7fa81643ffa1
> [/lib/x86_64-linux-gnu/libc.so.6]
> 0x7fa81634f4cd
> 0xfffffffffffffffe
> 
>   Code: -32603 
> [Error - 4:29:39 PM] Request textDocument/foldingRange failed.
>   Message: CONSTRAINT_ERROR
> [/net/homes/icolesa/.vscode-server/extensions/adacore.ada-21.0.12/linux/ada_language_server]
> Lsp.Ada_Context_Sets.Context_Lists.First_Element at a-cdlili.adb:533
> Lsp.Ada_Context_Sets.Get_Best_Context at lsp-ada_context_sets.adb:88
> Lsp.Ada_Handlers.On_Folding_Range_Request at lsp-ada_handlers.adb:1510
> Lsp.Error_Decorators.Folding_Range_Request at lsp-error_decorators.adb:45
> Lsp.Error_Decorators.On_Folding_Range_Request at lsp-error_decorators.adb:197
> Lsp.Servers.Handle_Request at lsp-servers-handle_request.adb:235
> Lsp.Servers.Processing_Task_Type.Process_Message at lsp-servers.adb:1072
> Lsp.Servers.Processing_Task_TypeT at lsp-servers.adb:1148
> [/net/sdp/homes/icolesa/.vscode-server/extensions/adacore.ada-21.0.12/linux/libgnarl-2019.so]
> 0x7fa816a413f4 system__tasking__stages__task_wrapper at ???
> [/lib/x86_64-linux-gnu/libpthread.so.0]
> 0x7fa81643ffa1
> [/lib/x86_64-linux-gnu/libc.so.6]
> 0x7fa81634f4cd
> 0xfffffffffffffffe
> 

Environment:
 - version: 21.0.12-dbg
 - OS: Debian GNU/Linux 10 (buster)
 - gnat version: GNAT Community 2019 (20190517-83)
 - editor: VS Code 1.45.1

For the moment I cannot reproduce the above error using a small example. Is there any advice you can give me in order to find out how to reproduce that error using a small example?
Thanks.

**Comment by AdrienBoulanger** [comment]
Hi Calinil,

The second issue is probably a side effect of the first so let's focus on this one.
Does your project hierarchy contain an aggregate project with another aggregate project inside?
I am suspecting an unwind issue in the algorithm used to get the list of projects. I will try to reproduce the issue from my side.

**Comment by 1ma** [comment]
I'm also experiencing this issue, and indeed I have 2 projects: one to build a static library and one for the command line executables that use it. [Here's the source, right now it's very minimal](https://github.com/1ma/radatracer).

On this project you should be able to reproduce it with the latest stable version of VSC and the Ada plugin.

**Comment by AdrienBoulanger** [comment]
Hi,

I have tested your project and I can reproduce the issue because als.projectFile was not defined.
When opening a folder containing multiple project files (.gpr), the ALS will complain and you should see the following popup:

```
    More than one .gpr found.
    Note: you can configure a project through the ada.projectFile setting.
```

The solution for this case is:
- create a .vscode directory
- inside it, create a file settings.json

See below the content of the file on my system:

```
$ cat .vscode/settings.json 
{
    "ada.trace.server": "verbose",
    "ada.projectFile": "radatracer.gpr"
}
```

If the issue still persist or you already have this settings then please let me know.

**Comment by 1ma** [comment]
Thanks Adrien.

I've added this file and restarted VSC, but the problem persists. If I create the `src/foo.ads` file and start typing the word "package" these are the verbose traces I now get.

By the way, I forgot to mention my environment:

OS: Ubuntu 18.04.4
GNAT version: FSF GNAT 7.5.0 (provided by Ubuntu's default `gnat-7` package)
Editor: Visual Studio Code 1.46.1
Extension version: 21.0.12

I've noticed @calinil 's version is 21.0.12*-dbg* and his stack traces contain code references, but on a cursory look I couldn't see how to get this version from VSC's marketplace. Let me know if it'd help pinpointing the problem.

```
[Trace - 12:16:07 PM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///home/marcel/workspace/radatracer/src/foo.ads",
        "version": 11
    },
    "contentChanges": [
        {
            "text": "p"
        }
    ]
}


[Trace - 12:16:07 PM] Sending request 'textDocument/completion - (65)'.
Params: {
    "textDocument": {
        "uri": "file:///home/marcel/workspace/radatracer/src/foo.ads"
    },
    "position": {
        "line": 0,
        "character": 1
    },
    "context": {
        "triggerKind": 1
    }
}


[Trace - 12:16:07 PM] Received response 'textDocument/completion - (65)' in 16ms. Request failed: CONSTRAINT_ERROR
[/home/marcel/.vscode/extensions/adacore.ada-21.0.12/linux/libadalang.so]
0x7fe9ec850698
[/home/marcel/.vscode/extensions/adacore.ada-21.0.12/linux/ada_language_server]
0x9a7622
0xa034e8
0x7da62c
0x7e2505
0x7a62da
0x7d72d6
0x7d630b
[/home/marcel/.vscode/extensions/adacore.ada-21.0.12/linux/libgnarl-2019.so]
0x7fe9e95753f4
[/lib/x86_64-linux-gnu/libpthread.so.0]
0x7fe9e899a6d9
[/lib/x86_64-linux-gnu/libc.so.6]
0x7fe9e82a788d
0xfffffffffffffffe
 (-32603).
[Error - 12:16:07 PM] Request textDocument/completion failed.
  Message: CONSTRAINT_ERROR
[/home/marcel/.vscode/extensions/adacore.ada-21.0.12/linux/libadalang.so]
0x7fe9ec850698
[/home/marcel/.vscode/extensions/adacore.ada-21.0.12/linux/ada_language_server]
0x9a7622
0xa034e8
0x7da62c
0x7e2505
0x7a62da
0x7d72d6
0x7d630b
[/home/marcel/.vscode/extensions/adacore.ada-21.0.12/linux/libgnarl-2019.so]
0x7fe9e95753f4
[/lib/x86_64-linux-gnu/libpthread.so.0]
0x7fe9e899a6d9
[/lib/x86_64-linux-gnu/libc.so.6]
0x7fe9e82a788d
0xfffffffffffffffe

  Code: -32603 
[Trace - 12:16:07 PM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///home/marcel/workspace/radatracer/src/foo.ads",
        "version": 14
    },
    "contentChanges": [
        {
            "text": "pack"
        }
    ]
}


[Trace - 12:16:07 PM] Sending request 'textDocument/foldingRange - (66)'.
Params: {
    "textDocument": {
        "uri": "file:///home/marcel/workspace/radatracer/src/foo.ads"
    }
}


[Trace - 12:16:07 PM] Received response 'textDocument/foldingRange - (66)' in 2ms.
Result: []


[Trace - 12:16:07 PM] Sending request 'textDocument/codeAction - (67)'.
Params: {
    "textDocument": {
        "uri": "file:///home/marcel/workspace/radatracer/src/foo.ads"
    },
    "range": {
        "start": {
            "line": 0,
            "character": 4
        },
        "end": {
            "line": 0,
            "character": 4
        }
    },
    "context": {
        "diagnostics": []
    }
}


[Trace - 12:16:07 PM] Received response 'textDocument/codeAction - (67)' in 0ms.
Result: []


[Trace - 12:16:08 PM] Sending request 'textDocument/documentSymbol - (68)'.
Params: {
    "textDocument": {
        "uri": "file:///home/marcel/workspace/radatracer/src/foo.ads"
    }
}


[Trace - 12:16:08 PM] Received response 'textDocument/documentSymbol - (68)' in 1ms.
Result: []
```

**Comment by AdrienBoulanger** [comment]
I can reproduce the completion issue: the completion request will return a constraint_error when editing an empty file/an empty node => we will fix that.
Note: this is a different issue from the initial one about project handling.

**Comment by AnthonyLeonardoGracio** [comment]
The completion issue is now solved, thanks for reporting it @calinil !
