### ISSUE TITLE
Visual Studio Code debugging?

### ISSUE THREAD

**Issue by 1ma** [AdaCore/ada_language_server#468]
Hi,

I just wanted to know if integrated debugging of Ada source code in Visual Studio Code is a planned feature for the [VSC extension](https://marketplace.visualstudio.com/items?itemName=AdaCore.ada), or whether if this feature would fit in the scope of the extension at all.

Thanks.

**Comment by Ales-hon-ne** [comment]
Hi, debugging is working with manual settings.
On windows I use 2 files for it:
**.vscode\tasks.json**
`{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Build",
            "type": "shell",
            "command": "<path to gprbuild.exe>",
            "args": [
                "${workspaceFolder}\\<project name>.gpr",
                "-f",
                "-cargs",
                "-g"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}`
**.vscode\launch.json**
`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Build & debug",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/obj/<exe name>.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "<path to gdb.exe>",
            "preLaunchTask": "Build",
            "setupCommands": [
                {
                    "description": "Autoformatting",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        },
    ]
}`
And also you need enable breakpoints for all files in VSCode preferences.

**Comment by 1ma** [comment]
It took a while to get around this but it works just fine, thank you.

[Here's a gist file](https://gist.github.com/1ma/8453a224ab3ba427ae746fd56a4893c4) that I created for future reference for myself, with a bit more clear instructions.
