### ISSUE TITLE
Missing lal_tools.gpr dependency

### ISSUE THREAD

**Issue by timlag1305** [AdaCore/ada_language_server#476]
I'm looking at the following line in the 21.0.12 release:
https://github.com/AdaCore/ada_language_server/blob/07b8d50a3d249d0e6ac7bce913da7941538fe82d/gnat/lsp_server.gpr#L19

Where does this `lal_tools.gpr` come from? The build fails without it and it doesn't seem to be provided by https://github.com/AdaCore/libadalang-tools

**Comment by ogorodnik** [comment]
Hello,
libadalang-tools provide it. It is located in libadalang-tools/src/lal_tools.gpr 
For building ALS you need to add the location of this project to GPR_PROJECT_PATH environment variable
