### ISSUE TITLE
Missing syntax highlighting for certain keywords

### ISSUE THREAD

**Issue by manthonyaiello** [AdaCore/ada_language_server#495]
In 21.0.13, there are a few keywords that receive no syntax highlighting at all. They are, at least:

- of
- in
- not
- and
- or

Here's an example that captures most of these:
![image](https://user-images.githubusercontent.com/806089/87471952-2ceef400-c5ed-11ea-9ca5-58b6597a8d82.png)

Note that `in` is also unhighlighted in other contexts (e.g., subprogram signatures):
![image](https://user-images.githubusercontent.com/806089/87472034-4b54ef80-c5ed-11ea-8e39-bd5eeac96e82.png)

**Comment by reznikmm** [comment]
I'm closing this, because ALS implements semantic tokens, rule-based highlighting isn't used any more and I don't have ideas how to fix it.
