### ISSUE TITLE
Mixed syntax highlighting for compound keywords

### ISSUE THREAD

**Issue by manthonyaiello** [AdaCore/ada_language_server#496]
In 21.0.13, there are some compound keywords that received mixed syntax highlighting. These are at least:

- for all
- for some
- end loop
- end if

Examples:
![image](https://user-images.githubusercontent.com/806089/87472961-c66ad580-c5ee-11ea-9b3f-2dc2bc0535cb.png)
![image](https://user-images.githubusercontent.com/806089/87473032-dda9c300-c5ee-11ea-8bbd-ef2ea11ba342.png)

I suspect that this is related to #436, but wonder if it would be possible to modify the tokenizer to simply treat these as distinct tokens in the short term?

Alternatively, while I like the idea of having distinct colors for things like subprogram declarations, I'll note that this is not the default in GNAT Studio. Here's an example in GNAT Studio:
![image](https://user-images.githubusercontent.com/806089/87473949-49d8f680-c5f0-11ea-8f17-336220f050e1.png)

And the same example in VS Code:
![image](https://user-images.githubusercontent.com/806089/87474118-9290af80-c5f0-11ea-9e35-2d50ce0a9965.png)

**Comment by reznikmm** [comment]
I'm closing this, because ALS implements semantic tokens, rule-based highlighting isn't used any more and I don't have ideas how to fix it.
