### ISSUE TITLE
Syntax highlighting of declare statement

### ISSUE THREAD

**Issue by manthonyaiello** [AdaCore/ada_language_server#497]
In 21.0.13, I find the syntax highlight of the declare statement to be somewhat surprising:
![image](https://user-images.githubusercontent.com/806089/87474227-c9ff5c00-c5f0-11ea-8022-7aeba3674eab.png)

I can imagine this was done on purpose, but felt it was worth asking: is the idea that, since declare introduces new identifiers, it should get the same syntax highlighting as a subprogram declaration/definition? That kinda makes sense to me, except that a for loop also introduces new identifiers, yet its syntax highlighting matches other control-flow statements. Of course, arguably, the declare statement is not about control flow, so ... I'm back to thinking this makes sense.

Nevertheless, having the highlighting color change mid-subprogram is a bit surprising to me.

**Comment by reznikmm** [comment]
I'm closing this, because ALS implements semantic tokens, rule-based highlighting isn't used any more and I don't have ideas how to fix it.
