### ISSUE TITLE
Crash attempting to load libgmp on darwin

### ISSUE THREAD

**Issue by manthonyaiello** [AdaCore/ada_language_server#498]
In 21.0.13, the server crashes repeatedly on startup with the following message:

```
dyld: Library not loaded: /usr/local/opt/gmp/lib/libgmp.10.dylib
  Referenced from: /Users/tony/.vscode/extensions/adacore.ada-21.0.13/darwin/libadalang.dylib
  Reason: image not found
[Info  - 4:46:09 PM] Connection to server got closed. Server will restart.
```

This happens five times in a row with identical timestamps - but the server does seem to be working, at least as far as basic syntax highlighting goes. 

The error is accurate: I definitely do not have libgmp (any version) in /usr/local/opt. I'm not sure why the server would assume I would, in fact. On my machine (macOS 10.15), /usr/local/opt is entirely filled with symlinks to Cellar-installs of things that I've installed with homebrew.

That directory is owned by my user; was the server supposed to be able to put the missing library there when it installed itself? 

I'll note that I don't see anything in the README suggesting that I ought to have install libgmp.

**Comment by manthonyaiello** [comment]
This bug persists in 21.0.14:

```
dyld: Library not loaded: /usr/local/opt/gmp/lib/libgmp.10.dylib
  Referenced from: /Users/tony/.vscode/extensions/adacore.ada-21.0.14/darwin/libadalang.dylib
  Reason: image not found
```

I'll note that, after the server has crashed five times, VS Code gives up. The result is that only syntax highlighting is available for Ada files.

**Comment by reznikmm** [comment]
@manthonyaiello 
Could you run this:
```
install_name_tool -change /usr/local/opt/gmp/lib/libgmp.10.dylib @rpath/libgmp.10.dylib /Users/tony/.vscode/extensions/adacore.ada-21.0.14/darwin/libadalang.dylib
```
Doe this help?

**Comment by manthonyaiello** [comment]
@reznikmm yes, this fixes the problem. 

Also, the ALS is _really cool_ when it actually works! I had no idea what I was missing!

**Comment by reznikmm** [comment]
@manthonyaiello Thank you for reporting the problem!
