### ISSUE TITLE
Output window interrupting workflow

### ISSUE THREAD

**Issue by danwinslow** [AdaCore/ada_language_server#517]
Hi Folks.
I am continually interrupted by the output window getting various errors. Is it possible to turn that off? Apologies for using an issue to essentially just ask a question, but I wasn't sure where else to post.

Can I post what I get? Sure, but it happens every 2-3 minutes at least, all kinds of different things. You can find the latest example at the end.
Can I post example source code that reproduces? Yes, if I wanted to I could, although -- I don't want to spend the extra effort on that if there's a way to stop it flashing the output window to the top all the time. I use the terminal windows for building and I don't like having to reselect the 'terminal' tab 100 times in an editing session. That is not an exaggeration.
I like the server, it does a fine job and gives me almost all I want. I don't want to disable it, but I'm getting close.

Thanks
Dan

`[Error - 10:05:27 AM] Request textDocument/codeAction failed.
  Message: CONSTRAINT_ERROR
[c:\Users\Dan\.vscode\extensions\adacore.ada-21.0.14\win32\libadalang\libadalang.dll]
0x1e033ae
[c:\Users\Dan\.vscode\extensions\adacore.ada-21.0.14\win32\ada_language_server.exe]
0xc90034
0xc906a3
0xc8e6fa
0xcb9b7b
0xcc305a
0xc19367
0xc57391
0xc563b5
[c:\Users\Dan\.vscode\extensions\adacore.ada-21.0.14\win32\libgnarl-2020\libgnarl-2020.dll]
0x69894aaa
[C:\WINDOWS\System32\KERNEL32.DLL]
0x7ffdcf4a7bd2
[C:\WINDOWS\SYSTEM32\ntdll.dll]
0x7ffdd0e0ce4f

  Code: -32603 
[Error - 10:13:23 AM] Request textDocument/completion failed.
  Message: PROGRAM_ERROR
[c:\Users\Dan\.vscode\extensions\adacore.ada-21.0.14\win32\libgnat-2020\libgnat-2020.dll]
0x67504593
[C:\WINDOWS\SYSTEM32\ntdll.dll]
0x7ffdd0e411cd
[C:\WINDOWS\SYSTEM32\ntdll.dll]
0x7ffdd0e0a207
[C:\WINDOWS\SYSTEM32\ntdll.dll]
0x7ffdd0e3fe3c
[c:\Users\Dan\.vscode\extensions\adacore.ada-21.0.14\win32\libadalang\libadalang.dll]
0x1e773f3
[c:\Users\Dan\.vscode\extensions\adacore.ada-21.0.14\win32\libadalang\libadalang.dll]
0x1e85c50
[c:\Users\Dan\.vscode\extensions\adacore.ada-21.0.14\win32\libadalang\libadalang.dll]
0x1e8517c
[c:\Users\Dan\.vscode\extensions\adacore.ada-21.0.14\win32\ada_language_server.exe]
0xbdf12c
0xcb457d
0xcba1a3
0xcc30bc
0xc1a1e0
0xc57391
0xc563b5
[c:\Users\Dan\.vscode\extensions\adacore.ada-21.0.14\win32\libgnarl-2020\libgnarl-2020.dll]
0x69894aaa
[C:\WINDOWS\System32\KERNEL32.DLL]
0x7ffdcf4a7bd2
[C:\WINDOWS\SYSTEM32\ntdll.dll]
0x7ffdd0e0ce4f

  Code: -32603`

**Comment by reznikmm** [comment]
Hello @danwinslow .

> Is it possible to turn that off?

May be there is some configuration on VS Code side. Ada Language Server (ALS) doesn't have such a configuration.

We prefer to fix all errors in ALS, so we are not interested to hide any errors on server side. We would suggest users to open bug reports in case of errors. This would help us to fix errors.

For instance, we have recently fixed an error in `textDocument/completion` request. You can install the latest build from [there].

[there]: https://bintray.com/reznikmm/ada-language-server/download_file?file_path=ada-21.0.999.vsix

**Comment by danwinslow** [comment]
Will do, thank you, Maxim.
