### ISSUE TITLE
Update VSCode extension link in README

### ISSUE THREAD

**Issue by btmalone** [AdaCore/ada_language_server#528]
The link for the VSCode extension is outdated and points to an older extension that isn't working (20.0.999 vs 21.0.15). This was confusing as I assumed it was linked to the latest version of the extension.
```
We also provide [Visual Studio Code](https://code.visualstudio.com/)
[extension as .vsix file](https://dl.bintray.com/reznikmm/ada-language-server/ada-20.0.999.vsix).
```
I would either remove the link entirely and instruct the user to search for the extension in the VSCode marketplace or update it to point to the proper VSCode extenstion.

**Comment by reznikmm** [comment]
Yes, indeed. The 20.0.999 link is outdated. It should be 21.0.999. We will fix the README.md

Thank you!
