### ISSUE TITLE
Support for Old-Style File Endings

### ISSUE THREAD

**Issue by rconnorjohnstone** [AdaCore/ada_language_server#529]
I'm relatively new to ada programming, so apologies if this is something that's already been accounted for and I just can't find the appropriate settings, but when using ALS in the built-in neovim lsp on lines such as:

```ada
separate (Foo.Bar)
```

I get the error: `file "foo-bar.adb" not found`. My understanding is that this is the modern naming scheme for an ada project, but my company uses an old naming scheme. Instead we would have a file called `foo.bar.2.ada`. Is there a way to have the language server recognize this other naming scheme?

**Comment by reznikmm** [comment]
Yes, if you can express your naming schema in the project file. See [documentation](https://docs.adacore.com/gprbuild-docs/html/gprbuild_ug/gnat_project_manager.html#naming-schemes) for details. In short you should have in the project file something like this:

```ada
package Naming is
  for Casing               use "lowercase";
  for Dot_Replacement      use ".";
  for Spec_Suffix ("Ada")  use ".1.ada";
  for Body_Suffix ("Ada")  use ".2.ada";
end Naming;
```
