### ISSUE TITLE
Visual Studio Code "gpr-aware" problemMatcher ?

### ISSUE THREAD

**Issue by JHag6694** [AdaCore/ada_language_server#541]
Hi 
Start to evaluate ALS using the Visual Studio Code extension.
In the build task provided , problemMatcher is set to "$ada"

If I use the same task with my own projects, it sems that it will only let me jump to the correct file/line when the build task displays an error if .gpr and  .adb are in the same folder - as only the source file base name is displayed and problemMatcher is not "gpr-aware"

Am I right or did I miss something ?

**Comment by setton** [comment]
You're right @JHag6694 - at the moment I would pass `-gnatef` to gprbuild to emit full paths in error messages, this should work until a project-aware problemMatcher is implemented.

**Comment by JHag6694** [comment]
Thanks @setton for the option. Works fine

**Comment by terids** [comment]
I'm was having the same issue, but adding -gnatef to my build args doubles up my path as in the image..

![screenshot1709](https://user-images.githubusercontent.com/10546876/106214189-307f4c80-61c6-11eb-89d8-85e72629f064.png)

Any hint as to what I can change to get the problem matcher working correctly? This is my tasks.json..

![screenshot1710](https://user-images.githubusercontent.com/10546876/106214243-4f7dde80-61c6-11eb-9219-d00c95461b2b.png)

Thanks for the great plugin! :)

**Comment by setton** [comment]
Hello @terids - unfortunately this doesn't exist yet - we will need to write some code that processes the .gpr file and gets the list of file from it, in order to match base name to file name... we plan to work on this, but we don't have a date in mind yet.

**Comment by JHag6694** [comment]
Hello @terids 
If you use -gnatef, you should use a problemMatcher where fileLocation is set to absolute.

Here attached, you will find my tasks.json which is working fine.

[tasks.json.txt](https://github.com/AdaCore/ada_language_server/files/5897605/tasks.json.txt)

**Comment by terids** [comment]
@JHag6694 the absolute path did it for me, thanks so much for that :)

**Comment by reznikmm** [comment]
I've added a "auto-detected tasks" that work well with "$ada" problem matcher using absolute file names (`-gnatef` option):

https://user-images.githubusercontent.com/6430719/113403445-559f5f80-93af-11eb-9110-326cdf4f202d.mp4

**Comment by reznikmm** [comment]
I think this works now (with `-gnatef` help).
