### ISSUE TITLE
Fedora Linux - Open file "Request has failed" every time

### ISSUE THREAD

**Issue by alisonken1** [AdaCore/ada_language_server#572]
Whenever I open a file, this message pops up.

System: Fedora 32 Linux

Output window:

[Error - 7:10:58 PM] Request textDocument/documentSymbol failed.
  Message: CONSTRAINT_ERROR
[.vscode/extensions/adacore.ada-22.0.1/linux/ada_language_server]
0xc88be3
0xc9e355
0xd625ed
0xd82fd6
0xd884e4
0xcb54d8
0xceb556
0xcea52d
[.vscode/extensions/adacore.ada-22.0.1/linux/libgnarl-2020.so]
0x7f883083a958
[/lib64/libpthread.so.0]
0x7f88301f7430
[/lib64/libc.so.6]
0x7f8830101911
0xfffffffffffffffe

  Code: -32603 
[Error - 7:10:58 PM] Request textDocument/foldingRange failed.
  Message: CONSTRAINT_ERROR
[.vscode/extensions/adacore.ada-22.0.1/linux/ada_language_server]
0xc88be3
0xc9e355
0xd516e1
0xd7fbf3
0xd8824a
0xcba680
0xceb556
0xcea52d
[/home/ken/.vscode/extensions/adacore.ada-22.0.1/linux/libgnarl-2020.so]
0x7f883083a958
[/lib64/libpthread.so.0]
0x7f88301f7430
[/lib64/libc.so.6]
0x7f8830101911
0xfffffffffffffffe

  Code: -32603

**Comment by reznikmm** [comment]
@alisonken1, could you try to specify project file? You can add setting `ada.projectFile` or create in the folder `.vscode/settings.json` file: 

```
cat .vscode/settings.json 
{
    "ada.projectFile": "/path/to/project.gpr"
}
```

Does this help?

**Comment by alisonken1** [comment]
Thanks.

Apparently I had it set incorrectly in the wrong spot.
