### ISSUE TITLE
How to run a program without debugger; possible launch.json issue

### ISSUE THREAD

**Issue by oscarrutt** [AdaCore/ada_language_server#583]
Getting started with Visual Studio Code and Ada Language Server at the same time is brutally difficult.

The Sample Code download is virtually documentation-free and one is left trying to figure out a myriad of json files at both the editor level and at the Ada Language Server level.

I would be really happy to discover how to run an Ada program without the debugger. The only launch.json file provided conveniently allows for debugging but how does one just run the program without debugging? Please augment either the provided launch and task and gpr files or provide explicit instructions so that simple running of the program is possible  as the VSC docs say should happen when one presses Control-F5. I have done this for years using TextMate and it was relatively straightforward so I assume the same is true for VSC but I'm just not getting it yet. Perhaps the ALS download could be augmented to include Build and Run, Build and Debug, and just Build, out of the box.

**Comment by setton** [comment]
Hello @oscarrutt - thank you for the suggestion. We plan to improve this in the future.

**Comment by reznikmm** [comment]
For example, the C/C++ extension uses the Terminal for [Running the build](https://code.visualstudio.com/docs/cpp/config-linux#_running-the-build). It's very flexible approach, because the user can pass command line options, redirect input/output and the program even can use text UI.

It's possible to do the same with Ada extension.

**Comment by oscarrutt** [comment]
Thank you, Maxim. I managed to get some things working by borrowing from my long-time TextMate set-up which was really the work of someone else's Ada efforts at the time. I'm happy with my set-up now but there was a long learning curve.

**Comment by reznikmm** [comment]
1. Press `` Ctrl+` `` to open a terminal
2. Type executable and arguments if any: `./hello_world`
