### ISSUE TITLE
Upload to VS Code Marketplace

### ISSUE THREAD

**Issue by Entomy** [AdaCore/ada_language_server#59]
As the extension has been created and is usable, how about uploading it to the [VS Code Marketplace](https://marketplace.visualstudio.com/) for easier discovery and use?

**Comment by setton** [comment]
Hi @Entomy, thanks for the heads-up! Yes, it's definitely something we're planning to do, and will do as soon as we have made progress on a few items first (perhaps implement at least textDocument/typedefinition, textDocument/implementation)... and also testing - we're only getting started with testing on big projects. Pending this, we don't consider this usable quite yet.

**Comment by Entomy** [comment]
Well that's what the Preview tag is for, but sure. I eagerly await trying it out.

**Comment by setton** [comment]
Watch this space :)
