### ISSUE TITLE
Publish the extension adacore.ada also on https://open-vsx.org/ for the Web based IDE

### ISSUE THREAD

**Issue by jgueytat** [AdaCore/ada_language_server#621]
Hi everyone,

thanks for the great job about the LSP !! There is a lot of projects now taking advantage of the web development thanks to the VSCode project. https://theia-ide.org/ is now a commonly used SDK for the Web based IDE. It uses exactly the same VSCode plugin. The only thing to do is to not publish the extension only on VSCode but also on https://open-vsx.org/.

https://github.com/open-vsx/publish-extensions

[Eclipse Che](https://www.eclipse.org/che/), [Gitpod.io](https://gitpod.io/) or [Red Hat CodeReady Workspaces](https://developers.redhat.com/products/codeready-workspaces/overview) would have a great benefit if you share also your work on this registry.

Gitpod.io is a wonderful place to test your extension as they have a deep integration with Github, Gitlab and BitBucket.

Hope to be able to install your extension on Gitpod.io really soon !
Best Regards,

**Comment by setton** [comment]
Thanks @jgueytat for the heads-up! We're having a look.

**Comment by jgueytat** [comment]
I plan to setup a project for Ada exactly the same way I did for the C++. Clicking on the button bellow will open https://bitbucket.org/jgueytat/helloworld_in_c/src/master/ on http://gitpod.io.

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://bitbucket.org/thalesaleniaspace/helloworld_in_c/src/master/)

I'll setup [the same for Ada](https://jgueytat@bitbucket.org/jgueytat/helloworld_in_ada.git) soon : 

- [ ] VSCode
- [ ] VSCode Remote
- [ ] Gitpod finally ;)

Do you have a docker image ready for the Ada development ? Just for speeding my investigation.

**Comment by setton** [comment]
That would be awesome. A very good incentive for us to push the extension to open-vsx.org...

**Comment by setton** [comment]
Regarding docker, we don't have an official one for GNAT Community, but there are quite a lot of them available out there already. I don't know which one to recommend :)

**Comment by jgueytat** [comment]
I found what I was looking for :

- https://hub.docker.com/r/dgautherot/gnat-community
- https://github.com/dgautherot/docker-gnat-community

**Comment by jgueytat** [comment]
VSCode and VSCode Remote work both like a charm.

The project [HelloWorld in Ada](https://bitbucket.org/jgueytat/helloworld_in_ada/src/master/) is ready for further tests with Gitpod once your extension will be published. I would be glad if you give it a try !

[![Gitpod ready-to-code](https://img.shields.io/badge/Gitpod-ready--to--code-blue?logo=gitpod)](https://gitpod.io/#https://bitbucket.org/jgueytat/helloworld_in_ada/src/master/)

**Comment by jgueytat** [comment]
https://www.youtube.com/watch?v=XWDArhNOXRo

**Comment by setton** [comment]
@jgueytat we have done the preliminary steps - we'll publish shortly and see how it goes.

**Comment by setton** [comment]
Hi @jgueytat - @reznikmm has just pushed the extension `AdaCore.ada v22.0.5` on the Open VSX registry. Please let us know if you're able to use it, we're very keen to see if it works!

**Comment by reznikmm** [comment]
@jgueytat, I've tested it on gitpod and it works!

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://bitbucket.org/reznikmm/helloworld_in_ada/src/master/)

**Comment by jgueytat** [comment]
Trying it also ! The Docker image I used seems overkill. But at least it's enough to test the extension. :)

**Comment by jgueytat** [comment]
It's working like a charm. :) In case you want to test the latest VSCode API you can still switch to code instead of Theia.
https://www.gitpod.io/docs/feature-preview/#default-ide

Thanks a lot !
