### ISSUE TITLE
Crash on hover with tiny MWE

### ISSUE THREAD

**Issue by oscarrutt** [AdaCore/ada_language_server#654]
I think I posted this at the bottom of an old thread so I'm opening a new ticket. Sorry for any confusion.

Consider this tiny program:
```Ada
with Ada.Numerics.Long_Real_Arrays;
use  Ada.Numerics.Long_Real_Arrays;
procedure dumpme is   
    f : Real_Vector(1 .. 2);  
    b : Integer;
begin
    for i in f'range(1) loop -- Removing (1) stops the crash.
        b := i;
        -- f(i) := Long_Float(i); -- Removes the warning but not the crash.
    end loop;
end dumpme;
```

With the Ada Language Server 22.0.6 (current in the Marketplace) running in Visual Studio Code 1.55.0 running in macOS, hover the cursor over elements of the line `b := i;` and you will get a crash of the ALS. As noted in the comments, removing the optional (1) from f'range(1) stops the crash. This problem also appears when using f'range(2) when f is a Real_Matrix and the (2) is not optional.

Jerry

**Comment by reznikmm** [comment]
@oscarrutt Thank you for the bug report. I'm unable to reproduce it on my Linux machine unfortunately.
Could you to set traces to `verbose` and try again? Just open user settings / extension / Ada configuration find there
```
Trace: Server
Traces the communication between VSCode and the language server.
```
and set it to verbose.
Then open Output (`Ctrl+K Ctrl+H`) chose `Ada Language Server` and find there any output after `textDocument/hover` request (after the crash).

**Comment by reznikmm** [comment]
What is your Mac OS version?

I suspect it could be result of Mac OS incomparability. Git Hub Action builds ALS on Mac OS 10.15. If you have older Mac OS, could you try to replace `libgmp.10.dylib` in `.vscode/extensions/adacore.ada-22.0.6/darwin/` with your own version of `libgmp.10.dylib`? It could be found in Homebrew.

**Comment by oscarrutt** [comment]
@reznikmm Thanks for looking at this. Here is the verbose trace file. I didn't edit it so you will find the textDocument/hover part about halfway. Some notes:

I noticed that there can be crashes when also hovering over parts of the for-loop as well as the next line. Indeed, if I am interpreting the trace correctly, the crash appears to have happened then, although I thought I was hovering over parts of the b := i line.

The file name has changed and appears in the trace as dumpme_crash.adb.

I notice that since I made the original post, VSCode has politely updated itself to 1.55.1 without telling me.

Jerry

P.S. This github page refuses to render a preview of my comment so I don't know if you will be able to see this. It also is having trouble attaching the file.
[hover-crash-trace.txt.zip](https://github.com/AdaCore/ada_language_server/files/6282595/hover-crash-trace.txt.zip)

**Comment by oscarrutt** [comment]
@reznikmm I am running macOS 10.11.6. Yes it is older but the newest that Apple supports on my machine.

I found `libgmp.10.dylib` in my MacPorts installation and also in Julia 1.5. I renamed the one in the ALS extension and put a symlink from the MacPorts version alongside. After about  minute of testing on the MWE and some simple variations I am unable to get a crash. So it looks like you found the problem. I will leave the symlink there and expect to have problems maybe when I next upgrade ALS.

Thanks!

Jerry

**Comment by reznikmm** [comment]
You are welcome! Thank you for the tiny MWE.

To keep records, there is dylib loading error in the trace:

```
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/jerrybauck/.vscode/extensions/adacore.ada-22.0.6/darwin/libgmp.10.dylib
  Expected in: /usr/lib/libSystem.B.dylib
```
