### ISSUE TITLE
Wrong highlighting of text after "new X"

### ISSUE THREAD

**Issue by 1ma** [AdaCore/ada_language_server#657]
Small fish, but still.

![error](https://i.imgur.com/p7lkptJ.png)

VS Code `1.55.1` and AdaCore.ada `22.0.6`

Repro code:

```ada
with Ada.Numerics;
with Ada.Text_IO;

procedure Example is
   type Foo is range 0 .. 10;

   subtype Bar is Foo range 0 .. 4;

   type Baz is new Foo range 5 .. 10;

   type Radian is new Float range 0.0 .. 2.0 * Ada.Numerics.Pi;
begin
   null;
end Example;
```

**Comment by reznikmm** [comment]
I'm closing this, because ALS implements semantic tokens, rule-based highlighting isn't used any more and I don't have ideas how to fix it.
