### ISSUE TITLE
code navigation not working

### ISSUE THREAD

**Issue by hillsmLM** [AdaCore/ada_language_server#659]
Definition, Declaration, References etc not working.
what has to be present for this functionality?  *.ali?  if so where to set path to find?

**Comment by reznikmm** [comment]
The Ada Language Server doesn't use `.ali` files at all. But to have the navigation working you should provide a project file (`.gpr`). If you use the VS Code then you can [configure it](https://github.com/AdaCore/ada_language_server#configuration) in the `.vscode/settings.json` file or using VS Code UI.

**Comment by hillsmLM** [comment]
Thanks that worked.

On another note how do I get the gnatpp?
Installed the rest of the tools from gcc-gnat


Scott M Hill
Software Engineer
Rotary and Mission Systems (RMS)
589 Independence Road
Hurlburt Field, Florida 32544
Office:   (850) 374-9275
E-mail LM:  ***@***.***

From: Maxim Reznik ***@***.***>
Sent: Monday, April 12, 2021 3:45 AM
To: AdaCore/ada_language_server ***@***.***>
Cc: Hill, Scott M1 (US) ***@***.***>; Author ***@***.***>
Subject: EXTERNAL: Re: [AdaCore/ada_language_server] code navigation not working (#659)


The Ada Language Server doesn't use .ali files at all. But to have the navigation working you should provide a project file (.gpr). If you use the VS Code then you can configure it<https://github.com/AdaCore/ada_language_server#configuration> in the .vscode/settings.json file or using VS Code UI.

**Comment by hillsmLM** [comment]
I downloaded the community version from AdaCore to get gnatpp but how do I get VSCode to run it.  It no longer seems to be trying to.

Thanks.


Scott M Hill
Software Engineer
Rotary and Mission Systems (RMS)
589 Independence Road
Hurlburt Field, Florida 32544
Office:   (850) 374-9275
E-mail LM:  ***@***.***

From: Maxim Reznik ***@***.***>
Sent: Monday, April 12, 2021 3:45 AM
To: AdaCore/ada_language_server ***@***.***>
Cc: Hill, Scott M1 (US) ***@***.***>; Author ***@***.***>
Subject: EXTERNAL: Re: [AdaCore/ada_language_server] code navigation not working (#659)


The Ada Language Server doesn't use .ali files at all. But to have the navigation working you should provide a project file (.gpr). If you use the VS Code then you can configure it<https://github.com/AdaCore/ada_language_server#configuration> in the .vscode/settings.json file or using VS Code UI.
