### ISSUE TITLE
VS Code extension is not aware of sources managed by Alire

### ISSUE THREAD

**Issue by 1ma** [AdaCore/ada_language_server#668]
## Scenario

A project bootstrapped by Alire can depend on "crates" from the Alire registry through the usual `with "crate.gpr";` statements in your GPR file. Then, if instead of building your project with `gprbuild` you use `alr build`, Alire takes care of downloading any dependencies into the project root directory (under `alire/`) and silently sets the appropriate `GPR_PROJECT_PATH` for `gprbuild` so that your GPR file can see and build these sources as if they were in any well-known location of your system.

However, the Ada extension can't see this third party code that lives inside the project's working directory.

## Real Example

https://github.com/1ma/radatracer

The repository is organized in 2 project files, one for library code and another for executable programs. The latter depends on the library GPR file and "aunit.gpr", managed by Alire. If we clone the repository and run `alr build` Alire will download AUnit 21.0.0 under `alire/cache/dependencies/aunit_21.0.0_d6561681` and build the executables successfully, including `aunit_harness`. But if we open VSCode the plugin will show this error, and navigation for AUnit types and functions will not work:

![example](https://i.imgur.com/bpIXRnt.png)

(Note: the `ada.projectFile` setting is enforced to `executables.gpr` in `.vscode/settings.json`)

**Comment by 1ma** [comment]
A nasty side effect of this error I didn't notice before: it breaks code navigation (Ctrl+Clicking symbols).

**Comment by reznikmm** [comment]
Hello @1ma  This issue duplicates #503, I guess.
How should ALS find that the project uses `alire`?

**Comment by 1ma** [comment]
Sorry, I saw it but I thought it was more of a philosophical discussion and didn't want to hijack it with an issue.

Regarding your question, maybe ALS could check if the current project contains any `alire.toml` file, and do something from there.

**Comment by Fabien-Chouteau** [comment]
Alire has a `alr edit` command that can start you favorite editor in the context of the crate.
The default is to use GNATstudio, but you can configure it to start VScode. If that helps.

**Comment by pyjarrett** [comment]
I've been using `alr config --set editor.cmd "code ."` pretty successfully, since it sets the environment prior to startup, including `GPR_PROJECT_PATH`.  The big issue I run into is that the GPR project file for the extension is per-workspace, so I have to change the GPR when I work on different projects, but it works well when it is set.

**Comment by 0rzech** [comment]
IMHO, it would still be better to make ALS Alire-aware. The reason are polyglot IDEs and editors. Launching such program with language-specific command seems a bit awkward, given one can switch to entirely different kind of project inside running instance. Also, many people launch IDEs and editors with GUI launchers and such workaround forces these people to alter launchers or to create command aliases. @1ma's suggestion to detect `alire.toml` seems right way to do it. At least this is how rust-analyzer does it with `Cargo.toml`, AFAIK.

**Comment by reznikmm** [comment]
Please try VS Code Ada extension 23.0.15. It should work now.
