### ISSUE TITLE
Binary images are forbidden

### ISSUE THREAD

**Issue by jaroslawblak** [AdaCore/ada_language_server#678]
I have tried to use binary image links to get one for MAC OS but I got 403 forbidden. (Tried also for linux image)
Any ideas?
![image](https://user-images.githubusercontent.com/26309796/116136514-afefbf80-a6d2-11eb-94f2-36fbe86d8665.png)

**Comment by reznikmm** [comment]
Take a look [here](https://bintray.com/reznikmm/ada-language-server/ada-language-server/22.0.999#files).
Unfortunately BinTray will stop this service on 1 May 2021. We are developing another solution.

**Comment by jaroslawblak** [comment]
Unfortunately provided link has the same effect

**Comment by reznikmm** [comment]
@jaroslawblak Works for me :confused: Could you try a command line tool?
```
curl -L -o macOS-22.0.999.tar.gz https://bintray.com/reznikmm/ada-language-server/download_file?file_path=macOS-22.0.999.tar.gz
```

**Comment by jaroslawblak** [comment]
Great, with curl it worked. I also tried today via link to BinTray and it also worked.  Seems that it was like temporary issue on their side. Thank you :)
