### ISSUE TITLE
Indentation problem on function call

### ISSUE THREAD

**Issue by carloxff** [AdaCore/ada_language_server#690]
Hi,

If we have a function call like this
```ada
V_RESULT :=
  F_FUNCTION
    (V_PARAM_1 => 2.0,
     V_PARAM_2 => 4.0,
     V_PARAM_3 => 5.0);
```
Now, we add an extra indentation for the whole block (select + tab). The result is:

```ada
  V_RESULT :=
    F_FUNCTION
      (V_PARAM_1 => 2.0,
      V_PARAM_2 => 4.0,
      V_PARAM_3 => 5.0);
```

The second and subsequent parameters are aligned with the parenthesis, instead of with the first parameter.

Greetings!

**Comment by petacreepers23** [comment]
Hello.

I have the same coding style as @carloxff described. It would be nice to know if this is configurable.

Thanks.

**Comment by carloxff** [comment]
Hello,

I have no Pretty_Printer setting in the gpr file and no specific options
are passed to the formatter.

I'm using the extension in Visual Studio Code.

Thanks for your help.

Regards,
  Carlos.

**Comment by AnthonyLeonardoGracio** [comment]
> ```ada
> ```ada
> V_RESULT :=
>   F_FUNCTION
>     (V_PARAM_1 => 2.0,
>      V_PARAM_2 => 4.0,
>      V_PARAM_3 => 5.0);
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

Ok, thanks for the info.

Note that pressing `tab` does not use the Ada Language Server formatter: it will let VS Code ident the code itself, without executing the `textDocument/formatting` LSP request. To use our formatter your should execute the `Format Selection` command instead (`Ctrl+K Ctrl+F` by default in VS Code).

By using `Format Selection` and having the proper settings in your `.gpr` file, you will get what you want.

Regards,
