### ISSUE TITLE
Constant "Imprecise Fallback" Popups When Editing

### ISSUE THREAD

**Issue by SMerrony** [AdaCore/ada_language_server#691]
First of all: thanks for creating this extension - it's great to be able to work in Ada in such a familiar environment.

I'm using v22.0.7 of the extension in the version 1.55 of VS Code.

But, when editing code I get a constant stream of pop-ups with `Imprecise fallback used to compute cross-references on entity at:` messages.

Is it possible to suppress these pop-ups?

Thanks.

**Comment by setton** [comment]
Hello @SMerrony - thank you for the kind words. Yes I would tend to agree that these messages are too noisy at the moment, we'll have a look.

**Comment by ChuanyuanLiu** [comment]
Thanks for creating this server

I also have the problem and the constant notification is very stressing.

My workaround is to toggle Zen Mode to silence notifications.

**Comment by petacreepers23** [comment]
Hello, 

I am also having that same problems with that same notifications. Not sure what can be causing them. It woukd be nice to be able to suppress them if possiblem

Thanks.
