### ISSUE TITLE
Inconsistent and/or confusing keyword coloring

### ISSUE THREAD

**Issue by oscarrutt** [AdaCore/ada_language_server#693]
As always, thanks for this great extension.

I'm getting inconsistent keyword coloring in  Visual Studio Code 1.56.0.

I have edited my settings.json file so that the  "Visual Studio Light" suits me. Within this file, the part that I have edited is sort of like editor.tokenColorCustomizations -> Visual Studio Light -> keywords -> foreground -> my favorite keyword color. Let's say my favorite keyword color is red, ff0000. With this, only certain keywords are then red and the rest are blue--to my eye, the blue is 0000ff. If there is a pattern, it seems that "control" words such as for, loop, if, then, case and end loop are red. Others such as begin, end, procedure, function, package, with, use, are blue.

I see the same kind of segregation of keywords in e.g. the unmodified Monokai theme. I can see where it might be helpful to have this, the "control" words colored differently than the "executive" or whatever keywords, but why can't I change the color of the "executive" keywords, only the "control" keywords?

Is there another setting other than "keywords" that I need to set?

Also, I notice that the keyword "range" is always red regardless of how I set the above keyword setting. (In Monokai it is weird green, different than any other keywords.) Maybe there is a separate coloring for attributes. Cool. But how do I set it?

On reflection I think that perhaps none of the behavior I have noted is a bug except being unable to set the "executive" colors. So maybe there are Ada-specific syntax colorings that are not conveniently revealed in settings.json.

**Comment by reznikmm** [comment]
AFAIK you can change a token of any kind [using textMateRules](https://code.visualstudio.com/docs/getstarted/themes#_editor-syntax-highlighting)
```
{
    "ada.projectFile": "gnat/vss_text.gpr",
    "editor.tokenColorCustomizations": {
        "[Default Dark+]": {
            "textMateRules": [
                {
                    "scope": "keyword.ada",
                    "settings": {
                        "foreground": "#FF0000",
                        "fontStyle": "bold"
                    }
                }
            ],
            "keywords": "#FF0000"
        }
    }
}
```

Consider to use [Scope Inspector](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#scope-inspector) to find needed scope identifiers.
