### ISSUE TITLE
Function names on RHS of assignments get the wrong color

### ISSUE THREAD

**Issue by oscarrutt** [AdaCore/ada_language_server#695]
Function names appearing on the right-hand side of assignment statements get a different coloring than the same names in the function definition. In the first case, the color appears to be some kind of default or the same as variables, where in the second case the color is as defined in settings.json. Visual Studio Code 1.56.0.

**Comment by reznikmm** [comment]
The syntax highlighting was developed by the community. Feel free to send a pull request if you know how to fix this issue.

**Comment by oscarrutt** [comment]
I don't know how to fix this.

**Comment by reznikmm** [comment]
I'm closing this, because ALS implements semantic tokens, rule-based highlighting isn't used any more and I don't have ideas how to fix it.
