### ISSUE TITLE
Weird shift of in-line comments in pop-over window of function definition.pdf

### ISSUE THREAD

**Issue by oscarrutt** [AdaCore/ada_language_server#696]
[Weird comment shift in pop-over window.pdf](https://github.com/AdaCore/ada_language_server/files/6462858/Weird.comment.shift.in.pop-over.window.pdf)
In the attached image file of a pop-over window when hovering over a particular function name, the in-line comments are shifted to the wrong line and one line is not colored properly. Visual Studio Code.

**Comment by reznikmm** [comment]
@oscarrutt Thank you for the bug report.
Unfortunately, I'm unable to reproduce this. Can you send us sources of a minimal reproducer?

**Comment by oscarrutt** [comment]
I'll wait to see if this appears in other instances before trying to work up a MWE.

**Comment by reznikmm** [comment]
After integrating with `gnatdoc` code, these pop-ups look different (better, I hope) now. So, I'm closing this issue.
