### ISSUE TITLE
compilation failure: laltools-refactor-rename.ads not found

### ISSUE THREAD

**Issue by TamaMcGlinn** [AdaCore/ada_language_server#709]
After fetching all the dependencies (with libadalang and langkit on the 'stable' branch, but this one on 'master', as [this note in the README](https://github.com/AdaCore/libadalang-tools/commit/3b438eb664ae07505a7167c83e409d353e17ca69) states), I tried `make` (after setting all the necessary GPR_PROJECT_PATH (*) but got:

```
lsp-ada_handlers.adb:58:06: error: file "laltools-refactor-rename.ads" not found

   compilation of lsp-ada_handlers.adb failed

gprbuild: *** compilation phase failed
```

I can see that file was renamed in [commit 4d752f7](https://github.com/AdaCore/libadalang-tools/commit/4d752f7952566d1a76e3ad0deb78699d59357b11) in the libadalang-tools repository, so I guess ada_language_server still needs to be updated for that.

# Note that might be helpful for those trying to build this:

(*) after running `make`:
```
lsp_client.gpr:19:06: imported project file "spawn" not found

$ find .. -type f -iname 'spawn.gpr'
../spawn/gnat/spawn.gpr
```

and finding each of the .gpr files necessary in the git repositories listed as dependencies, I came up with this:
```
GPR_PROJECT_PATH="$GPR_PROJECT_PATH:../spawn/gnat:../VSS/gnat:../libadalang-tools/src:../ada_language_server/subprojects/stubs" make
```
Of course, you could also globally set their paths in your GPR_PROJECT_PATH in a .bashrc or similar.

**Comment by reznikmm** [comment]
Try to get `edge` branch of `ada_language_server` instead of `master`.

**Comment by TamaMcGlinn** [comment]
Thank you, that works a bunch better, but I still get a compilation error:

```
lsp-ada_handlers.adb:221:12: warning: package "Location_Sets" is not referenced [-gnatwu]
lsp-ada_handlers.adb:227:12: warning: package "Index_Maps" is not referenced [-gnatwu]
(and, after deleting those:)
lsp-ada_handlers.adb:210:13: warning: function "Hash" is not referenced [-gnatwu]
```

(of course, I could turn off the warning, but it's hard to imagine this is what AdaCore does, so I probably still have the wrong version of something)

**Comment by reznikmm** [comment]
I guess these not referenced entities slipped through our CI, because we use an older compiler (GNAT CE 2020). Please update from `edge` and try again.

**Comment by TamaMcGlinn** [comment]
Thank you, that works.
