### ISSUE TITLE
Automatic line breaking does not work with the new 100-column punch cards

### ISSUE THREAD

**Issue by oscarrutt** [AdaCore/ada_language_server#719]
Version v22.0.7 of Ada Language Server apparently tries to break lines at column 80. This is a problem for me because I am using the new 100-column punch cards. 8^) Editing the line to my preferred width then becomes difficult.

I'm using Visual Studio Code 1.56.2 on macOS.

Is there a setting for this, or can the line breaking be turned off?

In addition, when trying to paste a bit of text into the line at the same time that ALS is trying to break the line causes malfunctions that are hard to describe. I've seen the part that I'm trying to paste just disappear, and I think also part of the line that has been wrapped has disappeared. I've had to resort to typing in what I'm trying to paste.

**Comment by reznikmm** [comment]
@oscarrutt 

What action in the VS Code causes line breaks in your file?

VS Code has a setting for "word wrap column", try to change it:

    "editor.wordWrapColumn": 100

The document/range formatting action uses `gnatpp` setting ([--max-line-length=](https://docs.adacore.com/gnat_ugn-docs/html/gnat_ugn/gnat_ugn/gnat_utility_programs.html#general-text-layout-control)). You can change it in the project file:

```
package Pretty_Printer is
   for Default_Switches ("ada") use ("--max-line-length=100");
end Pretty_Printer;
```

Tell us if this helps!
