### ISSUE TITLE
Where do I put the .vim/settings.json contents for Vim.

### ISSUE THREAD

**Issue by coffeebe4code** [AdaCore/ada_language_server#727]
I am using Coc Nvim on Vim 8. The language service runs, and provides all completion. However, when there are two .gpr files one for building the project, and the other for testing the project.

I see this output

![image](https://user-images.githubusercontent.com/78776922/123360396-dabf8e00-d532-11eb-8267-62da091255ce.png)

I tried adding it to the `coc-settings.json` like so
```
  
    "ada.projectFile": "build.gpr",
    "ada.scenarioVariables": {
        "GLFW_Version": "3",
        "GLFW_Lib": "-lglfw",
        "Windowing_System": "x11"
    },
    "languageserver": {
        "ada": {
          "command": "ada_language_server",
          "filetypes": ["ads", "adb", "ada"]
        },
    ...
```

I also tried adding a specific folder local to the project in `.vim/settings.json` I also tried this file to `~/.vim/settings.json` incase the language server was looking relative to home directory.

Any suggestions would be appreciated.

**Comment by reznikmm** [comment]
Hello @coffeebe4code,

Could you try this:
```
"languageserver": {
     "ada": {
       "command": "ada_language_server",
       "filetypes": ["ads", "adb", "ada"],
       "settings": {
          "ada.projectFile": "build.gpr"
       }
     }
```

**Comment by coffeebe4code** [comment]
```
    "ada": {
      "initializationOptions": {
        "ada.projectFile": "project.gpr",
        "projectFile": "project.gpr"
      },
      "settings": {
        "ada.projectFile": "project.gpr",
        "projectFile": "project.gpr"
      },
      "command": "ada_language_server",
      "filetypes": [
        "ads",
        "adb",
        "ada"
      ]
```
I have tried all these options as well, the language server still gives the same message

**Comment by coffeebe4code** [comment]
@reznikmm if you point me to the code, where the settings are imported, or where the file path is read. Could be through arguments on the server startup? I would be happy to look it over and add support for it if it doesnt exist.

**Comment by coffeebe4code** [comment]
I looked at the test suite, and noticed that ada property in settings, was using an object structure. Here is the config that worked.

```
  "languageserver": {
    "ada": {
      "settings": {
        "ada":{
          "projectFile": "build.gpr"
        }
      },
      "command": "ada_language_server",
      "filetypes": [
        "ads",
        "adb",
        "ada"
      ]
    },
...
```

**Comment by setton** [comment]
Thanks @coffeebe4code for the heads-up.
