### ISSUE TITLE
Starting client failed

### ISSUE THREAD

**Issue by pyjarrett** [AdaCore/ada_language_server#772]
I get the same error message, despite uninstalling/reinstalling the plugin.

## Error Message

```
[Error - 11:44:35 PM] Starting client failed
Launching server using command c:\Users\Paul\.vscode\extensions\adacore.ada-22.0.9\win32\ada_language_server failed.
```

## Local Fix

`C:\Users\Paul\.vscode\extensions\adacore.ada-22.0.9\win32\ada_language_server` exists, adding `.exe` onto the end allows the language server to start properly.

**Comment by reznikmm** [comment]
Hello @pyjarrett 

This has been fixed already in #767. We will publish a new version of the extension next week.
