### ISSUE TITLE
Completing elements not `with`'d adds "(invisible)"

### ISSUE THREAD

**Issue by pyjarrett** [AdaCore/ada_language_server#807]
Hitting enter with a partial completion inserts the text along with "(invisible)":

```ada
Base_Name : String := Ada.Directories.Simple_Name (invisible) (Name : String)
```

I know I need to add a `with` for `Ada.Directories` but I don't think completion should add "(invisible)".

**Comment by reznikmm** [comment]
Hello! 
Thank you for the new issue. I'm able to reproduce it! We will fix and publish a new version shortly.

**Comment by reznikmm** [comment]
This should work fine in 22.0.11
