### ISSUE TITLE
ALS 23.0.1 bombing in VSCode upon launch

### ISSUE THREAD

**Issue by oscarrutt** [AdaCore/ada_language_server#849]
This appears similar to https://github.com/AdaCore/ada_language_server/issues/654  #654 but without a clue as to how to use an alternate library. (In #654 it was libgmp.)

From VSCode, upgraded November 6, 2021:
Version: 1.62.0
Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
Date: 2021-11-03T15:24:41.297Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 15.6.0

I'm using ALS 23.0.1.

Upon launching VSCode and auto-re-opening my usual GNAT workspace but not doing anything else, ALS reports something like this:

```
dyld: lazy symbol binding failed: Symbol not found: ___darwin_check_fd_set_overflow
  Referenced from: /Users/jerrybauck/.vscode/extensions/adacore.ada-23.0.1/darwin/ada_language_server
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ___darwin_check_fd_set_overflow
  Referenced from: /Users/jerrybauck/.vscode/extensions/adacore.ada-23.0.1/darwin/ada_language_server
  Expected in: /usr/lib/libSystem.B.dylib

[Info  - 6:31:17 PM] Connection to server got closed. Server will restart.
[Error - 6:31:17 PM] Connection to server is erroring. Shutting down server.
```

and then basically repeats the above output sometimes multiple times. The little VSC pop-up sometimes says that there were five errors in three minutes etc.

The "referenced from" item is ada_language_server so I don't know how to fix the problem by symlinking to an alternate library like I did in #654. (BTW this problem still exists and I have to re-do the symlink every time ALS is updated.)

Yes, this is an older Darwin but it is the newest that Apple supports for my hardware.

**Comment by oscarrutt** [comment]
This problem does not appear in ALS 22.0.11, but does appear in 23.0.1.

**Comment by reznikmm** [comment]
@oscarrutt 

The reason for this is a change of `macos-latest` version in GitHub CI.

I propose you to build ALS yourself. I've prepared an alire index with dependencies and a short instruction:

https://github.com/reznikmm/als-alire-index/

Could you try?

**Comment by oscarrutt** [comment]
Thank you.

Building ALS myself would be a very heavy lift as I'm unfamiliar with or at best clumsy with most of the things involved in the instructions.

**Comment by reznikmm** [comment]
@oscarrutt 
Try to replace `ada_language_server` with [this binary](https://github.com/AdaCore/ada_language_server/releases/download/23.0.1/als_23.0.1_darwin.zip). Does it help?

**Comment by oscarrutt** [comment]
It does. With only a few minutes of testing it appears to fix the crash on launch.
