### ISSUE TITLE
bad highlighting for `renames` keyword

### ISSUE THREAD

**Issue by thvnx** [AdaCore/ada_language_server#869]
Hi,

The following `renames` uses don't correctly highlight in VSCode:

<img width="422" alt="Screenshot 2021-12-07 at 11 44 19" src="https://user-images.githubusercontent.com/8591473/145015579-12afac90-2e4f-46da-b813-78b50b506124.png">

Find below a reproducer:

```ada
with Ada.Text_IO;
with Ada.IO_Exceptions;

package Renam is
   package TIO renames Ada.Text_IO;

   generic package Enum_IO renames TIO.Enumeration_IO;
   EOF : exception renames Ada.IO_Exceptions.End_Error;
end Renam;
```

**Comment by reznikmm** [comment]
I'm closing this, because ALS implements semantic tokens, rule-based highlighting isn't used any more and I don't have ideas how to fix it.
