### ISSUE TITLE
Syntax highlighting for tasks

### ISSUE THREAD

**Issue by captain-haddock17** [AdaCore/ada_language_server#879]
Hi Ada lovers,

Syntax inside a task definition or body is not highlighted as for 'normal'/regular code.
What is OK:

* Keywords
* Comments

What I'd expect (if I might ...)

* Name of Task (definition , body)
* entry_declaration , highlighted as a subprogram (function, procedure), so it can be homogeneous with protected objects declarations.see [protected_operation_declaration](http://www.ada-auth.org/standards/12rm/html/RM-9-4.html)
* [select_alternative](http://www.ada-auth.org/standards/12rm/html/RM-9-7-1.html#S0233) (accept, delay, terminate) in a specific colour so that it would be easily readable
* Type colouring
* Object/variable colouring
* String value
* Character value
* =>

Sure it's WIP.

You will find some samples of some working code (Advent of Code 2021 Puzzle 04) on my [AdaForge GitHub](https://github.com/AdaForge/Advent_of_Code_2021/tree/main/puzzle_04))

Cheers,
and big thanks for your effort and commitment 😊😊😊
William

**Comment by reznikmm** [comment]
I'm closing this, because ALS implements semantic tokens, rule-based highlighting isn't used any more and I don't have ideas how to fix it. Reopen if this still doesn't work for you!
