### ISSUE TITLE
lsp_client_glib is not build/installed

### ISSUE THREAD

**Issue by atupone** [AdaCore/ada_language_server#885]
gnatstudio seems to depend on the lsp_client_glib.gpr being installed

**Comment by setton** [comment]
Hi @atupone - the lsp_client_glib is a very specialised project (supporting the integration of the language server in a GLib main loop) and is not meant to be used in the general case. The gnatstudio build expects a clone of this project under `subprojects/ada_language_server`. Don't hesitate to follow up under the gnatstudio project if needed!
