### ISSUE TITLE
Server initialization with project file

### ISSUE THREAD

**Issue by raja-s** [AdaCore/ada_language_server#9]
So [the server currently expects that a project contains the GPR file `gnat/lsp.gpr`](https://github.com/AdaCore/ada_language_server/blob/9d7cee6c95d2899fc8bc216d2b6c57c4ddf0ba46/source/ada/lsp-ada_contexts.adb#L107). Instead, we need to pass the project's GPR file path during initialization. This seems to me like the perfect use of [`InitializeParams`'s `initializationOptions` field](https://microsoft.github.io/language-server-protocol/specification#initialize).

I guess it would look more or less like this:
```
interface AdaInitializationOptions {
        /**
         * The path to the project's GPR file
         */
        gprFileUri: DocumentUri;
}
```
Any thoughts?

**Comment by raja-s** [comment]
Also, if we do choose to go with `initializationOptions`, we need to document its structure somewhere and update it in case we add additional fields

**Comment by reznikmm** [comment]
While experimenting I used custom `ada.project_file` workspace configuration option. It's easy to configure it with VSCode capabilities and easy to process with `Workspace_Did_Change_Configuration` handler.

May be it would be better to use this.

**Comment by raja-s** [comment]
Oh ok, but in that case the client needs to send a `workspace/didChangeConfiguration` notification after the server's response to the client's `initialize` request, and until then the server is kind of in a state where it can't successfully handle requests. Do you think that might be a problem?

What we can do is use both solutions as follows:
- The client includes the above described `AdaInitializationOptions` in the `InitializeParams` at initialization
- The client sends a `workspace/didChangeConfiguration` notification in case the GPR file being used changes

What do you think?

**Comment by raja-s** [comment]
Oh, and also we need to be able to send build parameters from the client to the server, so how about this:
```
interface AdaBuildParam {

        /**
         * The build parameter name
         */
        name: string;

        /**
         * The build parameter value
         */
        value: string;

}

interface AdaConfigSettings {

        /**
         * The path to the currently used project file
         */
        gprFileUri?: DocumentUri;

        /**
         * The currently used build parameters
         */
        buildParams?: AdaBuildParam[];

}
```

**Comment by TamaHobbit** [comment]
Does this mean we currently need to add a gnat/lsp.gpr file, in order to use ALS? I didn't see any mention in the readme of that, but project files don't seem to load for me. See issue #223
