### ISSUE TITLE
Building with dependencies

### ISSUE THREAD

**Issue by ceberly** [AdaCore/ada_language_server#902]
Hi, forgive this newbie question. I'm trying to build using the `make` command and I need dependencies like vss, etc. When I use `alr get --build vss` i get a vss project locally, but then re-running `make`, I still see that vss is missing. I understand *why* its missing, but its not really clear how one is supposed to set up dependencies for this (or really any) Ada project! I am very excited to start developing with Ada but i keep hitting this basic issue, feel free to refer me to the correct place as well!

Example output below:

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/99014/151976987-60eeb204-8031-4518-a7de-c5b66a36490b.png">

**Comment by glacambre** [comment]
@ceberly Have you added VSS' gprfiles to your $GPR_PROJECT_PATH? e.g. `GPR_PROJECT_PATH="$PWD/vss_22.0.0_b38t82ef/gnat/:$GPR_PROJECT_PATH" make`

**Comment by reznikmm** [comment]
Hi @ceberly,

Currently `alr` isn't well integrated into ALS building process. You can use alire to
* build `22.0.0` ALS version (from main alr index). Run `alr get --build ada_language_server`.
* build `23.0.2` ALS version (from [dedicated index](https://github.com/reznikmm/als-alire-index)). See that page for instructions.

Development ALS version doesn't support alire building for now. So, you should install all dependencies manually and this is rather complicated, I should say.

**Comment by ceberly** [comment]
Thanks this is very helpful. In general, if I wasn't using alire, should I add VSS' gprfiles to the GPR_PROJECT_PATH like @glacambre mentioned above?

**Comment by reznikmm** [comment]
Yes, you should do

    git clone https://github.com/AdaCore/VSS.git

and append path to VSS/gnat to `GPR_PROJECT_PATH`.
